### ISSUE TITLE
[BUG] - query_shard_exception/null_pointer_exception after upgrade to OpenSearch-Dashboards

### ISSUE THREAD

**Issue by ivantr5** [opensearch-project/OpenSearch-Dashboards#1182]
**Describe the bug**

After an upgrade to OpenSearch dashboards v.1.0.0 on AWS, in two environments we experience problems searching one of our indices:

Environment 1 (nonprod):

Type: query_shard_exception
Reason: failed to create query: field expansion matches too many fields, limit: 1024, got: 1115
Caused by type: illegal_argument_exception
Caused by reason: field expansion matches too many fields, limit: 1024, got: 1115

Environment 2 (prod):

null_pointer_exception
null

Error
    at Fetch._callee3$ (https://kibana-prod.common-blue.apfr-acm-common.ec1.aws.aztec.cloud.allianz/_dashboards/36473/bundles/core/core.entry.js:6:59575)
    at tryCatch (https://kibana-prod.common-blue.apfr-acm-common.ec1.aws.aztec.cloud.allianz/_dashboards/36473/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:33827)
    at Generator.invoke [as _invoke] (https://kibana-prod.common-blue.apfr-acm-common.ec1.aws.aztec.cloud.allianz/_dashboards/36473/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:37778)
    at Generator.next (https://kibana-prod.common-blue.apfr-acm-common.ec1.aws.aztec.cloud.allianz/_dashboards/36473/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:34966)
    at fetch_asyncGeneratorStep (https://kibana-prod.common-blue.apfr-acm-common.ec1.aws.aztec.cloud.allianz/_dashboards/36473/bundles/core/core.entry.js:6:52678)
    at _next (https://kibana-prod.common-blue.apfr-acm-common.ec1.aws.aztec.cloud.allianz/_dashboards/36473/bundles/core/core.entry.js:6:52994)

In order to resolve the problem, max_expansion_clause was increased in the AWS Opensearch cluster settings, but it didn't help.
Only workaround we found is to always specify field name + field value in the search, but it is not handy and it is causing troubles to search effectively.

**To Reproduce**

1.  OpenSearch- --> Discover--> Select index--> perform search either without query, or full text search.
2. One of the errors mentioned in the description popups up.

**Expected behavior**
The search should work as before the upgrade to OpenSearch Dashboards on AWS and no error should be present.
**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

No other plugins installed. 

**Screenshots**

Environment 1 (nonprod)

![image](https://user-images.githubusercontent.com/85614462/151342642-71415f36-ce30-4238-b083-4d1030bd484f.png)

![image](https://user-images.githubusercontent.com/85614462/151342761-c28cb3fc-65bb-4830-99e2-5f5a56976f94.png)

Environment 2 (prod)

![image](https://user-images.githubusercontent.com/85614462/151342490-8ad4ed11-dca8-41a3-bea9-39e3098c91d8.png)

![image](https://user-images.githubusercontent.com/85614462/151342558-47cffb08-5421-4fe7-a353-650249f8c390.png)

**Host/Environment (please complete the following information):**

AWS Elasticsearch -> 7.10.2
AWS Opensearch -Dashboards-> 1.0.0

**Additional context**

**Comment by ahopp** [comment]
@ivantr5 Can you confirm that you are using AWS Elasticsearch 7.10.2 & AWS Opensearch Dashboards 1.0.0. While this is might be technically possible on the versioning it is atypical. Are both of this actually on the AWS managed service?

**Comment by ivantr5** [comment]
I'll check once again with the team, but that is why I see when I check ElasticSearch status and the version in OpenSearch Dashboards console:

"name" : "1d9f276bd4eb20380059b374d3e407ed",
"cluster_name" : "239907433624:prod",
"cluster_uuid" : "kgxKDNWtSt2fpsulATTfRg",
"version" : {
"number" : "**7.10.2**"

![image](https://user-images.githubusercontent.com/85614462/152130984-2f0d2a8f-6b9a-4719-b8ff-fb5366f25d14.png)

What would be the recommended combination of versions, and would it help in the problem resolution?

**Comment by kavilla** [comment]
Hello @ivantr5 , are you able to create a curl request on `_search` with the same parameters and not get an error?

If you so we might need to re-route this issue to the OpenSearch repo.

**Comment by AndreyByhalenko** [comment]
I think i have the same issue.
Free search does not work in Dashboard after a while.
![Screen Shot 2022-02-17 at 8 46 14](https://user-images.githubusercontent.com/89009825/154433589-c1c47706-3b47-443d-98e3-62a26772ab99.png)
![Screen Shot 2022-02-17 at 8 46 07](https://user-images.githubusercontent.com/89009825/154433620-e94bd976-ac14-430f-8df6-a0932e92a080.png)

**Comment by CJBourassa** [comment]
I'm encountering the same issue as well. I created a new user, assigned them a role with permissions to read a specific index within a specific tenant, and encounter this error after clicking the Discover section as that user. That being said, the master user does not run into this issue if I switch to the same tenant and try to search logs via Discover. 
![image](https://user-images.githubusercontent.com/36799177/154760775-0d0122e7-78eb-4364-bb30-95a57dbf7c6f.png)

**Comment by ivantr5** [comment]
Hi @kavilla ,

I executed CURL and got the exception:

curl -XGET --user ...:'...'  https:/...:,443/logstash-prod-apigee-*/_search -H 'Content-Type: application/json' -d '{"query": {"query_string": {"query": "ABCDEFGHIJKL"}}}'

{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: field expansion for [*] matches too many fields, limit: 1024, got: 1154","index":"logstash-prod-apigee-2022.01.17","index_uuid":"jXaNhjuTQ622erRyFds6VQ"},{"type":"query_shard_exception","reason":"failed to create query: field expansion for [*] matches too many fields, limit: 1024, got: 1154","index":"logstash-prod-apigee-2022.01.18"

**Comment by kavilla** [comment]
Hello @ivantr5,, thanks for providing this.

It would appear this is a duplicate of this: https://github.com/opensearch-project/OpenSearch/issues/1513 related to the AWS managed solution of OpenSearch.

I will pass it to the OpenSearch repo.
