### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JeffBolle** [opensearch-project/OpenSearch-Dashboards#1203]
When attempting to create a Transform using the UI tool, there appears to be a script error that renders the UI completely blank when I am on the second step of selecting the fields to include in the transform.

**To Reproduce**
1. Go to Index Management -> Transform Jobs
2. Click on Create Transform Job
3. Enter index (I have tried multiple different indexes and I'm getting the same behavior) and target index
4. Click Next
5. On the next screen sometimes the table loads, sometimes the entire page appears blank.

**Expected behavior**
A table of values to select the relevant columns for my transform.

**OpenSearch Version**
OpenSearch 1.2.4

**Dashboards Version**
Dashboards 1.2.0

**Plugins**
All default

**Screenshots**
![image](https://user-images.githubusercontent.com/18576812/152279367-406444f2-2b63-41b8-8122-76a3db496627.png)

**Host/Environment (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - Chrome : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

**Additional context**

An error I'm seeing on the console is:
```
opensearch_index_management_dashboards#/transforms:352 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-75XtnrpDA0UHDMcl7S8lvswryIOd0RqgacRh0AMOgdk='), or a nonce ('nonce-...') is required to enable inline execution.
```
There are also some other errors in the console:

```
0osd-ui-shared-deps.@elastic.js:1 EuiButtonIcon requires aria-label or aria-labelledby to be specified because icon-only
      buttons are screen-reader-inaccessible without them.
m @ osd-ui-shared-deps.@elastic.js:1
50osd-ui-shared-deps.js:434 Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=renderCellValue for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at osd-ui-shared-deps.js:434:57818
    at $a (osd-ui-shared-deps.js:434:66589)
    at Ms (osd-ui-shared-deps.js:434:104803)
    at gl (osd-ui-shared-deps.js:434:90018)
    at fl (osd-ui-shared-deps.js:434:89943)
    at ol (osd-ui-shared-deps.js:434:87291)
    at osd-ui-shared-deps.js:434:45733
    at t.unstable_runWithPriority (osd-ui-shared-deps.js:442:3462)
    at Hi (osd-ui-shared-deps.js:434:45442)
    at Gi (osd-ui-shared-deps.js:434:45678)
ds @ osd-ui-shared-deps.js:434
core.entry.js:13 Detected an unhandled Promise rejection.
Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=renderCellValue for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
osd-ui-shared-deps.js:434 Uncaught (in promise) Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=renderCellValue for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at osd-ui-shared-deps.js:434:57818
    at $a (osd-ui-shared-deps.js:434:66589)
    at Ms (osd-ui-shared-deps.js:434:104803)
    at gl (osd-ui-shared-deps.js:434:90018)
    at fl (osd-ui-shared-deps.js:434:89943)
    at ol (osd-ui-shared-deps.js:434:87291)
    at osd-ui-shared-deps.js:434:45733
    at t.unstable_runWithPriority (osd-ui-shared-deps.js:442:3462)
    at Hi (osd-ui-shared-deps.js:434:45442)
    at Gi (osd-ui-shared-deps.js:434:45678)
```
Here is a screenshot of what my browser looks like:
![image|427x500](upload://qePBRw31hfdof8ZZTVUNuuIa6oN.png)

I'm unable to click any links and have to refresh the window to do anything in the transform again.

**Comment by kavilla** [comment]
Hey @JeffBolle, thanks for opening this.

I was able to recreate the behavior from picking either a source or target index being a system index (for example `.kibana`). But once I picked a data index to another data index, for example `opensearch_dashboards_sample_data_flights` to `opensearch_dashboards_sample_data_ecommerce` I didn't get the blank page.

Can you confirm that same behavior?

Will re-route to this to the ISM plugin. ISM team, if it turns out this behavior I believe we should prevent system indices from being selectable. I don't imagine we would want to be able to allow transforms on system indices from a user.

Thanks!
