### ISSUE TITLE
Node-Sass error on version 1.2.0 

### ISSUE THREAD

**Issue by korpx-z** [opensearch-project/OpenSearch-Dashboards#1277]
Following the developer guide to build tag 1.2.0 I get this error when running the `yarn start` step:

```
ERROR in ./public/index.scss?v7light (/home/opensearch/OpenSearch-Dashboards/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-1-1!/home/opensearch/OpenSearch-Dashboards/node_modules/postcss-loader/src??ref--6-oneOf-1-2!/home/opensearch/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-1-3!./public/index.scss?v7light)
       │          Module build failed (from /home/opensearch/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js):
       │          SassError: Top-level selectors may not contain the parent selector "&".
       │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
       │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
       │                  from line 1:9 of src/core/public/chrome/_index.scss
       │                  from line 5:9 of /home/opensearch/OpenSearch-Dashboards/src/core/public/index.scss
       │          >>   &.euiBody--headerIsFixed {
       │
       │             --^
       │
       │          SassError: SassError: Top-level selectors may not contain the parent selector "&".
       │                  on line 1:10 of src/core/public/chrome/ui/header/_index.scss
       │                  from line 1:9 of src/core/public/chrome/ui/_index.scss
       │                  from line 1:9 of src/core/public/chrome/_index.scss
       │                  from line 5:9 of /home/opensearch/OpenSearch-Dashboards/src/core/public/index.scss
       │          >>   &.euiBody--headerIsFixed {
       │
       │             --^
       │
       │              at Object.render [as callback] (/home/opensearch/OpenSearch-Dashboards/node_modules/sass-loader/dist/index.js:73:16)
       │              at Object.done [as callback] (/home/opensearch/OpenSearch-Dashboards/node_modules/neo-async/async.js:8067:18)
       │              at options.error (/home/opensearch/OpenSearch-Dashboards/node_modules/node-sass/lib/index.js:293:32)
       │           @ ./public/index.scss?v7light 2:26-254
       │           @ ./public/index.scss
       │           @ ./public/index.ts
       │           @ /home/opensearch/OpenSearch-Dashboards/packages/osd-optimizer/target/worker/entry_point_creator.js
**Host/Environment (please complete the following information):**
```
 - OS: linux/s390x 
 I know you don't officially offer support for this OS, but I this is a porting effort of mine and dashboards has been the only plugin causing me trouble in these attempts. I've been trying to solve this for a few days.

I'm not exactly hoping for an official fix to be added to the repo as I've been able to build this tag on x86 without issue, I'm just wondering what this might be considering the node-sass dependency is compatible with node version 10 and there is a commit against this repo that supposedly negated this error:
[mentioned here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/535)

Any ideas why I am seeing this error? Considering the changes made in the commit mentioned above are in place, I am unsure what I should do..

**Comment by tmarkley** [comment]
I haven't had a chance to stand up an instance with that OS to reproduce, but does this still occur for you with the latest changes in the `main` branch?

**Comment by tmarkley** [comment]
Hey @korpx-z, I'm closing this due to inactivity. Please feel free to re-open it if you're still having issues.
