### ISSUE TITLE
[BUG] Migration check on same version throws error while scaling Dashboards.

### ISSUE THREAD

**Issue by mihirsoni** [opensearch-project/OpenSearch-Dashboards#1303]
**Describe the bug**

Since OpenSource Dashboards has been forked and changed it's version to 1.0 the current migration logic checks the version and halt the startup. 

**To Reproduce**
* Start Dashboards with FGAC domain
* Create multiple tenants
* Add another node / container to existing Dashboards fleet (Blue / Green) . 
* Now the new container will complain that index needs to be migrated. 

**Expected behavior**
It should not throw this error

**OpenSearch Version**
1.0

**Dashboards Version**
1.0

**Plugins**

All plugins (FGAC included)

**Additional context**

Here is sample log error

```
{"type":"log","@timestamp":"2022-03-01T20:23:12Z","tags":["error","plugins","securityDashboards"],"pid":9630,"message":"Error: Index .kibana_-1085563064_some_random_name_1 belongs to a version of OpenSearch Dashboards that cannot be automatically migrated. Reset it or use the X-Pack upgrade assistant.\n    at assertIsSupportedIndex at Object.fetchInfo (rc/core/server/saved_objects/migrations/core/opensearch_index.js:82:10)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
```

**Comment by ahopp** [comment]
@mihirsoni Following up on this. Can you verify the cluster was health at the the the node was add?

Additionally, can you verify the mappings were correct and healthy? Our assumption is yes, but wanted to make sure.

**Comment by seraphjiang** [comment]
Thank you for reporting this issue. This issue has been open for over two years without recent activity, and multiple OpenSearch Dashboards releases have shipped since then with significant improvements and fixes.

We're closing this as part of a housekeeping effort to keep the backlog actionable. If this issue is still reproducible on a recent version of OpenSearch Dashboards (2.19+), please feel free to reopen this issue or file a new one with updated reproduction steps and version details.

We appreciate your contribution to OpenSearch!
