### ISSUE TITLE
Dashboards Discover blank after upgrade to 1.3.0

### ISSUE THREAD

**Issue by JeffBolle** [opensearch-project/OpenSearch-Dashboards#1363]
**Describe the bug**

After upgrading to OpenSearch Dashboards 1.3.0, users are unable to use the discover tab, although the Dashboard tab still works.

**To Reproduce**
0. Upgrade from a working 1.2.0 Dashboards installation
1. Go to The Discover tab
2. If no index patterns are loaded, the tab will load.
3. create an index pattern
4. Go back to the discover tab. 
5. See that nothing is there.

**Expected behavior**
To see the index pattern chooser and search results.

**OpenSearch Version**
1.3.0

**Dashboards Version**
1.3.0

**Plugins**
Standard install.

**Screenshots**
![Screenshot from 2022-03-18 17-19-07](https://user-images.githubusercontent.com/18576812/159084403-a2245ed5-e344-46b1-ae88-915fd91a817e.png)

Here is the error from the browser console:

osd-ui-shared-deps.js:434 TypeError: Cannot read properties of undefined (reading 'kueryQuerySyntax')
    at QueryBarTopRow (:5601/1/bundles/plugin/data/data.chunk.4.js:1:137586)
    at ua (:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:59332)
    at Ms (:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:104414)
    at gl (:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:90018)
    at fl (:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:89943)
    at ol (:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:87291)
    at :5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:45733
    at t.unstable_runWithPriority (:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:442:3462)
    at Hi (:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:45442)
    at Gi (:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:45678)
ds @ osd-ui-shared-deps.js:434

**Host/Environment (please complete the following information):**
 - OS: Dashboards docker container hosted on Google container optimized os.
 - Browser and version [e.g. 22]

Google Chrome | 99.0.4844.51 (Official Build) (64-bit)
-- | --
Revision | d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}
OS | Linux
JavaScript | V8 9.9.115.8
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

**Additional context**

I've heard from some users that they do not have the problem. However a large number do.

**Comment by JeffBolle** [comment]
I'm not sure how to adequately raise the awareness on this, but this is a terrible issue that has rendered Dashboards unusable for most of our users.  Attempts to downgrade to 1.2.0 were unsuccessful.  Any assistance with remediating or addressing this would be appreciated.

**Comment by kavilla** [comment]
Hello @JeffBolle,

Thank you for opening this issue! Sorry that you are seeing this issue.

Would you be willing share some information on all your index-pattern looks like? Did you successfully migrated from 1.0 to 1.1, and 1.1 to 1.2?  Or did you onboard with 1.2? There is an issue with caching: https://github.com/opensearch-project/opensearch-build/issues/1769 that you could be running into.

**Comment by JeffBolle** [comment]
I'm happy to share whatever is needed. 

I cleared out my personal .kibana tenant index and have been testing with that. When I clear it out I can load the discover tab, but as soon as I add any index pattern, I can no longer load the discover tab. 

I believe we started with OpenSearch 1.2. 

What should I try to mitigate the caching issue?

**Comment by kavilla** [comment]
If you are able to mitigate the caching issue and resolves it please let me know. If it is a caching issue then that's something we dropped the ball on it and we can work on prioritizing https://github.com/opensearch-project/opensearch-build/issues/1769

**Comment by JeffBolle** [comment]
I just loaded dashboards in an Incognito window and that worked! Thank you, I sincerely appreciate the help late in the day on a Friday. For now its definitely feasible to have our users flush their cache, but that gave us quite the scare!

**Comment by kavilla** [comment]
@JeffBolle, I really apologize for the caching issue. It was an huge oversight when we were building out our build system, I will ensure that for whatever next release that the cache breaker will be fixed. But thank you for opening this issue it really helps with making the case to prioritize the issue!

**Comment by JeffBolle** [comment]
@kavilla No worries! Hopefully this issue also helps others that run into it solve it quickly.  The 1.3.0 upgrade (to get continuous transforms) was a key step in our process of migrating from ElasticSearch 7.10.2 to OpenSearch.  We've now moved our largest data system over and so far it is going very smoothly, all things considered.  We appreciate the hard work being done by all of the teams involved.

**Comment by kavilla** [comment]
Thanks for migrating so quickly and thanks for opening this issue. I'm going to retitle it and pin into the repo for visibility.

**Comment by kavilla** [comment]
@JeffBolle, we have released `1.3.1` that should resolve the cache breaking issue.
