### ISSUE TITLE
[BUG] Unable to build Docker image as it relies on Centos 8 which is EOL

### ISSUE THREAD

**Issue by jgough** [opensearch-project/OpenSearch-Dashboards#1601]
**Describe the bug**

When I try to build the docker image from source with `yarn build --docker --release` I get the following error:
```
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

This seems to be because Centos 8 has reached EOL: https://techglimpse.com/failed-metadata-repo-appstream-centos-8/

Full output:
```
   │ERROR Error: Command failed with exit code 1: ./build_docker.sh
   │      The command '/bin/sh -c for iter in {1..10}; do       yum update --setopt=tsflags=nodocs -y &&       yum install --setopt=tsflags=nodocs -y         fontconfig freetype shadow-utils libnss3.so  &&       yum clean all && exit_code=0 && break || exit_code=$? && echo "yum error: retry $iter in 10s" &&       sleep 10;     done;     (exit $exit_code)' returned a non-zero code: 1
   │      8: Pulling from library/centos
   │      Digest: sha256:a27fd8080b517143cbbbab9dfb7c8571c40d67d534bbdee55bd6c473f432b177
   │      Status: Image is up to date for centos:8
   │      docker.io/library/centos:8
   │      Docker pull successful.
   │      Building: opensearch-dashboards-docker
   │      Sending build context to Docker daemon  96.17MB
   │      Step 1/31 : FROM centos:8 AS builder
   │       ---> 5d0da3dc9764
   │      Step 2/31 : COPY opensearch-dashboards-3.0.0-linux-x64.tar.gz /opt
   │       ---> a4a6daff21fc
   │      Step 3/31 : RUN mkdir /usr/share/opensearch-dashboards
   │       ---> Running in dab1c00e1938
   │      Removing intermediate container dab1c00e1938
   │       ---> f591e3c03373
   │      Step 4/31 : WORKDIR /usr/share/opensearch-dashboards
   │       ---> Running in e0892aa197ba
   │      Removing intermediate container e0892aa197ba
   │       ---> e7f1498afb7c
   │      Step 5/31 : RUN tar --strip-components=1 -zxf /opt/opensearch-dashboards-3.0.0-linux-x64.tar.gz
   │       ---> Running in 84f5fee9b4e2
   │      Removing intermediate container 84f5fee9b4e2
   │       ---> a7b6ae082e0b
   │      Step 6/31 : RUN chmod -R g=u /usr/share/opensearch-dashboards
   │       ---> Running in 5b6511b0ec9e
   │      Removing intermediate container 5b6511b0ec9e
   │       ---> ceb664a48988
   │      Step 7/31 : RUN find /usr/share/opensearch-dashboards -type d -exec chmod g+s {} \;
   │       ---> Running in 49db7fe1ddc0
   │      Removing intermediate container 49db7fe1ddc0
   │       ---> 2619da07120a
   │      Step 8/31 : FROM centos:8
   │       ---> 5d0da3dc9764
   │      Step 9/31 : EXPOSE 5601
   │       ---> Using cache
   │       ---> 4fb4514f4430
   │      Step 10/31 : RUN for iter in {1..10}; do       yum update --setopt=tsflags=nodocs -y &&       yum install --setopt=tsflags=nodocs -y         fontconfig freetype shadow-utils libnss3.so  &&       yum clean all && exit_code=0 && break || exit_code=$? && echo "yum error: retry $iter in 10s" &&       sleep 10;     done;     (exit $exit_code)
   │       ---> Running in 42d7fd10054a
   │      CentOS Linux 8 - AppStream                      134  B/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 1 in 10s
   │      CentOS Linux 8 - AppStream                      174  B/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 2 in 10s
   │      CentOS Linux 8 - AppStream                      110  B/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 3 in 10s
   │      CentOS Linux 8 - AppStream                      1.4 kB/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 4 in 10s
   │      CentOS Linux 8 - AppStream                      133  B/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 5 in 10s
   │      CentOS Linux 8 - AppStream                      937  B/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 6 in 10s
   │      CentOS Linux 8 - AppStream                      174  B/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 7 in 10s
   │      CentOS Linux 8 - AppStream                      728  B/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 8 in 10s
   │      CentOS Linux 8 - AppStream                       67  B/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 9 in 10s
   │      CentOS Linux 8 - AppStream                      174  B/s |  38  B     00:00
   │      Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
   │      yum error: retry 10 in 10s
   │          at makeError (/build/node_modules/execa/lib/error.js:59:11)
   │          at handlePromise (/build/node_modules/execa/index.js:114:26)
   │          at processTicksAndRejections (internal/process/task_queues.js:95:5)
   │          at async Promise.all (index 0)
   │          at watchStdioForLine (/build/src/dev/build/lib/watch_stdio_for_line.ts:75:3)
   │          at exec (/build/src/dev/build/lib/exec.ts:59:3)
   │          at runDockerGenerator (/build/src/dev/build/tasks/os_packages/docker_generator/run.ts:127:3)
   │          at Object.run (/build/src/dev/build/tasks/os_packages/create_os_package_tasks.ts:87:5)
   │          at execTask (/build/src/dev/build/lib/runner.ts:69:7)
   │          at run (/build/src/dev/build/lib/runner.ts:98:9)
   │          at buildDistributables (/build/src/dev/build/build_distributables.ts:129:5)

error Command failed with exit code 1.
```

The image being used seems to be coming from here:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/dev/build/tasks/os_packages/docker_generator/run.ts#L54

Given Centos 8 has reached EOL, does the container base image need updating to a different maintained base image?

**To Reproduce**
Try to build docker image on head version in `main` using the buld command `yarn build --docker --release`

**Expected behavior**
Expected docker image to be successfully built

**Dashboards Version**
main:HEAD

**Comment by jgough** [comment]
This is slightly odd to me as when I download the `opensearchproject/opensearch-dashboards:2.0.0-rc1` container it seems to be based on Amazon Linux 2.  Are the official images using a different build procedure?  Should I be building from source using a different command?

I managed to get it building from source with the above command by adding
```
# Switch over to centos vault as Centos 8 is EOL
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
```
to https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile#L52

But as in my previous comment I'm not sure the OpenSearch Dashboards image should continue to be based off Centos 8 if it is now EOL.

**Comment by ananzh** [comment]
I can reproduce the issue. 
and yes, the bug is due to Centos 8 is EOL

**Comment by ananzh** [comment]
Another quick fix would be replace it with AlmaLinux, Oracle Linux, or RockyLinux.
Some compare from my local:
```
anan@***:~$ docker run almalinux yum list available | wc -l
Unable to find image 'almalinux:latest' locally
latest: Pulling from library/almalinux
cdfe3ece1d98: Pulling fs layer
cdfe3ece1d98: Download complete
cdfe3ece1d98: Pull complete
Digest: sha256:e75030b68398783cfadf3880ccef63385e0f2dddc7a3214e7ab75647fda6fb32
Status: Downloaded newer image for almalinux:latest
6944
anan@***:~$ docker run rockylinux yum list available | wc -l
7021
anan@ip-***:~$ docker run oraclelinux:8 yum list available | wc -l
Unable to find image 'oraclelinux:8' locally
8: Pulling from library/oraclelinux
25cd53f41add: Pulling fs layer
25cd53f41add: Verifying Checksum
25cd53f41add: Download complete
25cd53f41add: Pull complete
Digest: sha256:cad3a3dc2dd9f03dec02642dce1f194562e7f21820bc36ceb9f7b070d337fb45
Status: Downloaded newer image for oraclelinux:8
9115

```
Use rockylinux as an example:

Update [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/src/dev/build/tasks/os_packages/docker_generator/run.ts#L54) from `'centos:8'` to `'rockylinux:latest'`.

```
$ docker run almalinux yum list available | wc -l
6944
$ docker run rockylinux yum list available | wc -l
7021
$ docker run oraclelinux:8 yum list available | wc -l
9115
```

Change [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/src/dev/build/tasks/os_packages/docker_generator/run.ts#L61) to `const imageTag = 'opensearchproject/opensearch-dashboards';`

Remove [this line](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/0000000000000000000000000000000000000000:/src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile#L37).

Then use `yarn build --docker --release` to create an image.

**Comment by ananzh** [comment]
However, I am a bit concerned and don't quite understand why do we need to maintain a docker generator and docker build in our code base? why do we care about docker's platform (ubi and centos)? 

There might be two use cases for docker:
1) CI
We already have [this doc](https://opensearch.org/docs/latest/opensearch/install/docker/) and our opensearch.org has a lot of examples. 
2) release
For release, we have Dockerfile [here](https://github.com/opensearch-project/opensearch-build/tree/main/docker/release/dockerfiles)

Do we need to maintain this docker generator? I think this might be some legacy codes when we don't have published dockers. Since docker platform is not important and we have docker files well written in opensearch.org, should we just remove this part of code (not fix it)?

**Comment by jgough** [comment]
We very much use the docker build in the code base as we have some custom modifications and are building Docker containers from source, so cannot use the published docker files.  Please don't remove this functionality from us unless there is an adequate alternative we can use to build from source and achieve this!

**Comment by ananzh** [comment]
Hey @jgough, don't worry. We just want to bring this to discuss and understand what are the user cases and requirements. You could see we do have multiple places of Dockerfile. Even in our OSD code base, we have /Dockerfile and /src/dev/build/tasks/os_packages/docker_generator. Meanwhile, we would like to discuss what is the purpose/use case for docker supporting specific system. If there is use cases, what systems do we want to support.

**Comment by kavilla** [comment]
[Triage]

My opinion we haven't been properly supporting this code. When we publish docker images for releases we utilize the [Build Repo](https://github.com/opensearch-project/opensearch-build).

However, with that said [this line](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/dev/build/tasks/os_packages/docker_generator/run.ts#L54), should be cleaned up to utilize what we expect. If the line is not properly setting `ubi` to `true` then default to an image. `docker.opensearch.org/ubi8/ubi-minimal:latest` doesn't exist and would fail but we have OpenSearch docker images that we can use. I'd prefer if we use the [OpenSearch Build Images ](https://hub.docker.com/r/opensearchstaging/ci-runner/tags) so what we publish officially can be utilized so we have a baseline of support.

**Comment by CPTNB** [comment]
I think the best path forward is to let users supply a base image via command line, defaulting to something super generic like ```ubuntu```.  We'd then redirect the ubi command to specify ```redhat/ubi8```.

Example:
```sh
yarn build --docker --base="rockylinux:8" --release
```

> use the [OpenSearch Build Images](https://hub.docker.com/r/opensearchstaging/ci-runner/tags)
I don't love this because we use several different images in that repo and it's not obvious which one is "default".  That means users would have to pick from those, which brings us to the same UX complexity as just letting them bring whatever they want. 
 Unless there's a good reason to restrict running dashboards exclusively on containers we own, I'd like to get out of the way.

If there is a "default" base image or preferred platform to run dashboards on, we should appoint it and use it as the default here.

**Comment by ananzh** [comment]
I agree with Captain that it is best to provide an option for user to request base image. However, there are two places that we need to be very specific for diff system:

1) package manager 
Currently, we support 'microdnf' for ubi and 'yum' for centos
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/src/dev/build/tasks/os_packages/docker_generator/templates/dockerfile.template.ts#L40

2) package manager usage
different package manager will have diff cmd
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/8c11eff94240169a87288710d0c3acaea6fd24fc/src/dev/build/tasks/os_packages/docker_generator/templates/Dockerfile#L53-L60

If we want to provide an option to user, this means we need to verify all the possibilities and work on their package manager, test and others.

How about we support one or two popular system? and provide developer guide some instructions to modify the system?

**Comment by ananzh** [comment]
Here is docker build from opensearch-build:
https://github.com/opensearch-project/opensearch-build/blob/main/docker/release/dockerfiles/opensearch-dashboards.al2.dockerfile

and this is the file to build our docker. You could modify it according to your needs.

If we don't require centos, @jgough, would the above file satisfy your need?

**Comment by jgough** [comment]
@ananzh I'm quite happy with any sensible base image (amazonlinux is fine) and the Dockerfile looks good.

I just like the fact here that:
1. Building the container is as simple as running `yarn build --docker --release`
2. I can simply build OpenSearch Dashboards with without having to download the additional `opensearch-build` repo which needs more dependencies and adds a lot more complexity to my build process
3. I can build a minimal version of OpenSearch Dashboards with no installed plugins (or more specifically, because of https://github.com/opensearch-project/security-dashboards-plugin/issues/857)
4. Selfish reason time - I actually fixed the build process here as it was broken when first released :-) https://github.com/opensearch-project/OpenSearch-Dashboards/pull/289

Maybe there's a way to reuse that Dockerfile in the OpenSearch Dashboards Repo when `yarn build --docker` is run - so it is both standardised and simple?

**Comment by lliu0947** [comment]
@ananzh I compiled the image according to your method, but when docker run, the following error appears: 
standard_init_linux.go:219: exec user process caused "permission denied"
libcontainer: container start initialization failed: standard_init_linux.go:219: exec user process caused "permission denied"

docker inspect :
"Created": "2022-06-15T07:05:45.001832533Z",
        "Loaded": "2022-06-15T15:05:44.999518638+08:00",
        "Container": "4688fcd2d524d9577848a5b599ea4a098bd137eb1d8ed04e03b7cc7b3483a182",
        "ContainerConfig": {
            "Hostname": "4688fcd2d524",
            "Domainname": "",
            "User": "opensearch-dashboards",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5601/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/share/opensearch-dashboards/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "OPENSEARCH_CONTAINER=true"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/usr/local/bin/opensearch-dashboards-docker\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:b3c0686adbfb9279a3f7bfdf9e98f14213ea0ef06e04da82d9c3ddea98e3f1e6",
            "Volumes": null,
            "WorkingDir": "/usr/share/opensearch-dashboards",
            "Entrypoint": [
                "/usr/local/bin/dumb-init",
                "--"
            ],
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2022-06-15T06:57:43.549Z",
                "org.label-schema.license": "ASL 2.0",
                "org.label-schema.name": "OpenSearch Dashboards",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://opensearch.org/",
                "org.label-schema.usage": "https://opensearch.org/",
                "org.label-schema.vcs-ref": "133f2b07ce8985796ddacb650ec7b18de97f8382",
                "org.label-schema.vcs-url": "https://github.com/opensearch-project/OpenSearch-Dashboards",
                "org.label-schema.vendor": "OpenSearch",
                "org.label-schema.version": "2.0.0-SNAPSHOT",
                "org.opencontainers.image.created": "2022-06-15T06:57:43.549Z",
                "org.opencontainers.image.documentation": "https://opensearch.org/",
                "org.opencontainers.image.licenses": "ASL 2.0",
                "org.opencontainers.image.revision": "133f2b07ce8985796ddacb650ec7b18de97f8382",
                "org.opencontainers.image.source": "https://github.com/opensearch-project/OpenSearch-Dashboards",
                "org.opencontainers.image.title": "OpenSearch Dashboards",
                "org.opencontainers.image.url": "https://opensearch.org/",
                "org.opencontainers.image.vendor": "OpenSearch",
                "org.opencontainers.image.version": "2.0.0-SNAPSHOT"
            },
            "Annotations": {
                "native.umask": "secure"
            }
        },
        "DockerVersion": "18.09.0",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "opensearch-dashboards",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5601/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/share/opensearch-dashboards/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "OPENSEARCH_CONTAINER=true"
            ],
            "Cmd": [
                "/usr/local/bin/opensearch-dashboards-docker"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:b3c0686adbfb9279a3f7bfdf9e98f14213ea0ef06e04da82d9c3ddea98e3f1e6",
            "Volumes": null,
            "WorkingDir": "/usr/share/opensearch-dashboards",
            "Entrypoint": [
                "/usr/local/bin/dumb-init",
                "--"
            ],
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "2022-06-15T06:57:43.549Z",
                "org.label-schema.license": "ASL 2.0",
                "org.label-schema.name": "OpenSearch Dashboards",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.url": "https://opensearch.org/",
                "org.label-schema.vcs-ref": "133f2b07ce8985796ddacb650ec7b18de97f8382",
                "org.label-schema.vcs-url": "https://github.com/opensearch-project/OpenSearch-Dashboards",
                "org.label-schema.vendor": "OpenSearch",
                "org.label-schema.version": "2.0.0-SNAPSHOT",
                "org.opencontainers.image.created": "2022-06-15T06:57:43.549Z",
                "org.opencontainers.image.documentation": "https://opensearch.org/",
                "org.opencontainers.image.licenses": "ASL 2.0",
                "org.opencontainers.image.revision": "133f2b07ce8985796ddacb650ec7b18de97f8382",
                "org.opencontainers.image.source": "https://github.com/opensearch-project/OpenSearch-Dashboards",
                "org.opencontainers.image.title": "OpenSearch Dashboards",
                "org.opencontainers.image.url": "https://opensearch.org/",
                "org.opencontainers.image.vendor": "OpenSearch",
                "org.opencontainers.image.version": "2.0.0-SNAPSHOT"
            },
            "Annotations": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 785711374,
        "VirtualSize": 785711374,

**Comment by seraphjiang** [comment]
Thank you for reporting this issue. This issue has been open for a long time without recent activity, and OpenSearch Dashboards has since moved to the 3.x release line (currently 3.6, with 3.7 upcoming). The last supported 2.x release is 2.19.x.

We're closing this as part of a housekeeping effort to keep the backlog actionable. If this issue is still reproducible on a supported version (2.19.x or 3.x), please feel free to reopen this issue or file a new one with updated reproduction steps and version details.

We appreciate your contribution to OpenSearch!
