### ISSUE TITLE
[BUG] Not able to run functional test on my MacOS

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/OpenSearch-Dashboards#2087]
**Describe the bug**

Clone repo and pull code, 

try to run functional test ciGroup1 on my local Mac, but got error, 

```
huanji@88665a37b322 huan-osd % node scripts/functional_tests.js --include ciGroup1

 warn ❗️❗️❗️
 warn ❗️❗️❗️
 warn ❗️❗️❗️
 warn    Don't forget to use `node scripts/build_opensearch_dashboards_platform_plugins` to build plugins you plan on testing
 warn ❗️❗️❗️
 warn ❗️❗️❗️
 warn ❗️❗️❗️
 info Running /Users/huanji/src/huan-osd/test/functional/config.js
 │ info Config loaded
 │ info Only running suites (and their sub-suites) if they include the tag(s): [ 'ciGroup1' ]
 │ info Installing from snapshot
     │ info version: 2.0.1
     │ info install path: /Users/huanji/src/huan-osd/.opensearch/opensearch-test-cluster
     │ info license: oss
     │ warn [opensearch-dashboards] already stopped

Snapshots are only available for Linux
    at exports.createCliError (/Users/huanji/src/huan-osd/packages/osd-opensearch/target/errors.js:33:17)
    at getArtifactSpecForSnapshotFromUrl (/Users/huanji/src/huan-osd/packages/osd-opensearch/target/artifact.js:210:11)
    at Function.getSnapshot (/Users/huanji/src/huan-osd/packages/osd-opensearch/target/artifact.js:298:32)
    at Object.installSnapshot [as downloadSnapshot] (/Users/huanji/src/huan-osd/packages/osd-opensearch/target/install/snapshot.js:73:35)
    at installSnapshot (/Users/huanji/src/huan-osd/packages/osd-opensearch/target/install/snapshot.js:105:21)
    at Cluster.installSnapshot (/Users/huanji/src/huan-osd/packages/osd-opensearch/target/cluster.js:178:15)
    at OpenSearchTestCluster.start (/Users/huanji/src/huan-osd/packages/osd-test/src/legacy_opensearch/legacy_opensearch_test_cluster.js:95:38)
    at runOpenSearch (/Users/huanji/src/huan-osd/packages/osd-test/src/functional_tests/lib/run_opensearch.js:56:17)
    at /Users/huanji/src/huan-osd/packages/osd-test/src/functional_tests/tasks.js:113:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at withProcRunner (/Users/huanji/src/huan-osd/packages/osd-dev-utils/target/proc_runner/with_proc_runner.js:45:9)
    at runTests (/Users/huanji/src/huan-osd/packages/osd-test/src/functional_tests/tasks.js:108:5)
    at /Users/huanji/src/huan-osd/packages/osd-test/src/functional_tests/cli/run_tests/cli.js:46:5
    at runCli (/Users/huanji/src/huan-osd/packages/osd-test/src/functional_tests/lib/run_cli.js:52:5)
    at Object.runTestsCli (/Users/huanji/src/huan-osd/packages/osd-test/src/functional_tests/cli/run_tests/cli.js:44:3)
```

**Expected behavior**

1. developer should be able to run any functional test from most popular OS (MacOS, Windows, Linux)
2. add documentation to list all environment variable which are supported and useful to run test e.g. `export TEST_OPENSEARCH_FROM=`

**Comment by ashwin-pc** [comment]
I agree, especially since this makes writing functional tests quite painful. What are the current limitations for enabling this?

**Comment by aoguan1990** [comment]
Duplicate Issue: [#2088](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2088)

**Comment by seraphjiang** [comment]
> 

the request is to ask for support Mac

**Comment by kavilla** [comment]
Triage: 

Thanks @seraphjiang perhaps we can get escalation on mac support on the build repo issue? https://github.com/opensearch-project/opensearch-build/issues/38

**Comment by joshuarrrr** [comment]
@kavilla is this closed via https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3537

**Comment by seraphjiang** [comment]
Thank you for reporting this issue. This issue has been open for a long time without recent activity, and OpenSearch Dashboards has since moved to the 3.x release line (currently 3.6, with 3.7 upcoming). The last supported 2.x release is 2.19.x.

We're closing this as part of a housekeeping effort to keep the backlog actionable. If this issue is still reproducible on a supported version (2.19.x or 3.x), please feel free to reopen this issue or file a new one with updated reproduction steps and version details.

We appreciate your contribution to OpenSearch!
