### ISSUE TITLE
dashboards doesn't understand " host.ip "  (possibly host.* ) , breaking the UI

### ISSUE THREAD

**Issue by anubisg1** [opensearch-project/OpenSearch-Dashboards#2274]
As per title,

i'm ingesting into opensearch 2.2.1 using logstash 8.4 with output-plugin 1.3.0
The data is ingested fine by opensearch but opensearch-dashboard doesn't like the host nested fields.

when visualized under discovery, it's only possible to see "host" with content being a json.
adding filters also generates errors.

Notice that host.* is valid according to ECS schema v1 and v8

document example:

```
{
  "_index": "network-2022.09.06",
  "_id": "E7NJFIMBJLv78azG6hjM",
  "_version": 1,
  "_score": null,
  "_source": {
    "log": {
      "syslog": {
        "date": "Sep  6 21:32:11",
        "severity": {
          "code": "6",
          "name": "Informational"
        },
        "procid": "10849",
        "appname": "logger",
        "priority": 182,
        "hostname": "TESTLB.sampled.com",
        "http_date": "06/Sep/2022:21:32:11 +0200"
      }
    },
    "message": "\"/mgmt/shared/inflate/available\" 200 2\n",
    "event": {
      "hash": "2183e9780a50d69fa2f96c413518e7974f9de423",
      "action": "ssl_acc"
    },
    "tags": [
      "f5"
    ],
    "user": {
      "name": "admin"
    },
    "type": "syslog",
    "@timestamp": "2022-09-06T19:32:11.987723836Z",
    "source": {
      "ip": "192.168.10.10"
    },
    "host": {
      "ip": "192.168.1.1"
    }
  },
  "fields": {
    "@timestamp": [
      "2022-09-06T19:32:11.987Z"
    ]
  },
  "sort": [
    1662492731987
  ]
}
```

the below is how dashboard displayed the data:

![image](https://user-images.githubusercontent.com/4518931/188723875-2dd8ecbf-2da0-4966-9486-ba88a5ef3f97.png)

and this is the error when for example adding the field as a filter

```
parsing_exception
[match_phrase] query does not support [ip]
Error
    at Fetch._callee3$ (https://opensearch.demo.com/4075/bundles/core/core.entry.js:15:584612)
    at tryCatch (https://opensearch.demo.com/4075/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:108326)
    at Generator.invoke [as _invoke] (https://opensearch.demo.com/4075/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:112277)
    at Generator.next (https://opensearchdemo.com/4075/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:109465)
    at fetch_asyncGeneratorStep (https://opensearch.demo.com/4075/bundles/core/core.entry.js:15:577704)
    at _next (https://opensearch.demo.com/4075/bundles/core/core.entry.js:15:578020)
```

**Comment by anubisg1** [comment]
Looking further into this, it seems that this is caused by an updated index pattern.

Coming from elastic i never had this problem before as new fields would be automatically refreshed, but with opensearch i had to manually refresh the index pattern fields, then the issue was solved

**Comment by kavilla** [comment]
[Triage]

Thanks @anubisg1!

We are looking at options to provide a better experience to provide a refreshed index pattern if new fields are inserted into OpenSearch.

@opensearch-project/opensearch-ux could we get assistance here?
