### ISSUE TITLE
Requesting suggestions on chromedriver for ppc64le

### ISSUE THREAD

**Issue by SonalMahambrey1** [opensearch-project/OpenSearch-Dashboards#3164]
As per my understanding chromedriver istallables are not available for power. On power we can skip the chromedriver in pacakage.json and can build the opensearch-dashboard, however for running functional test cases it tries to find chromedriver. 

Any thoughts or suggestion for integrating chromedriver binaries with the  opensearch-Dashboard.

**Comment by joshuarrrr** [comment]
@kavilla Is this related or a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1018?

**Comment by kavilla** [comment]
It is related. Like the core problem is the chromedriver but the suggestion here is that we download and bundle up a chromedriver.

I know reporting plugin used to download a chromium binary https://github.com/opensearch-project/opensearch-build/blob/1.3.7/scripts/components/reportsDashboards/build.sh#L120 and bundle it up. And we bundle up Node and release it as well. So the suggestion would be doing something similar?

Is that what you are suggesting @SonalMahambrey1?

@joshuarrrr, do you think there any cons to doing the suggestion here? Probably size and maintenance of sourcing a chromedriver.

**Comment by SonalMahambrey1** [comment]
I was looking at the approach suggested in [#1018](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1018), Installing** chromedriver-binary (https://pypi.org/project/chromedriver-binary/) via pip. However the main issue is chromedriver is not supported on power and is not available externally to download. As per my understanding github repo (https://github.com/danielkaiser/python-chromedriver-binary.git) is downloading binary from https://chromedriver.storage.googleapis.com/ and there is no support for power. Even if we install the chromedriver with this approach, it will not be supported on power architecture

**Comment by SonalMahambrey1** [comment]
**OS / architecture**
Debian Bullseye / ppc64le

Installed chromedriver which is available for ppc64le
export CHROMEDRIVER_FILEPATH=/usr/bin/chromedriver
export CHROMEDRIVER_SKIP_DOWNLOAD=true

Ran bootstrap command on openserachDashboard repo
_yarn osd bootstrap_

As expected, it skipped the chromedriver installation while attempting bootstrap and bootstrap was successful.

However, while running the functional test, it searched for the chromedriver at
"**OpenSearch-Dashboards/node_modules/chromedriver/lib/chromedriver/chromedriver**" even after setting the CHROMEDRIVER_FILEPATH


warn Error: **The specified executable path does not exist: /home/test/opensearch_project/OpenSearch-Dashboards/node_modules/chromedriver/lib/chromedriver/chromedriver**
     │          at new DriverService.Builder (/home/test/opensearch_project/OpenSearch-Dashboards/node_modules/selenium-webdriver/remote/index.js:319:13)
     │          at new ServiceBuilder (/home/test/opensearch_project/OpenSearch-Dashboards/node_modules/selenium-webdriver/chromium.js:174:5)
     │          at new ServiceBuilder (/home/test/opensearch_project/OpenSearch-Dashboards/node_modules/selenium-webdriver/chrome.js:180:5)
     │          at buildDriverInstance (/home/test/opensearch_project/OpenSearch-Dashboards/test/functional/services/remote/webdriver.ts:171:31)
     │          at attemptToCreateCommand (/home/test/opensearch_project/OpenSearch-Dashboards/test/functional/services/remote/webdriver.ts:300:42)
     │          at /home/test/opensearch_project/OpenSearch-Dashboards/test/functional/services/remote/webdriver.ts:355:31
     │          at Observable._subscribe (/home/test/opensearch_project/OpenSearch-Dashboards/node_modules/rxjs/src/internal/observable/defer.ts:59:15)
     │          at Observable._trySubscribe (/home/test/opensearch_project/OpenSearch-Dashboards/node_modules/rxjs/src/internal/Observable.ts:238:19)
     │          at attemptToCreateCommand (/home/test/opensearch_project/ker s^C-Dashboards/test/functional/services/remote/webdriver.ts:171:31)s:319:13)driv

Tried setting the path in npm config file and was expecting that it will take the custom path from config but didn't help
test@49533cf32e2f:~/opensearch_project/OpenSearch-Dashboards$ _npm config list_
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.17 node/v14.20.0 linux ppc64"

**; project config /home/test/opensearch_project/OpenSearch-Dashboards/.npmrc
chromedriver_filepath = "/usr/bin/chromedriver"

; userconfig /home/test/.npmrc
chromedriver_filepath = "/usr/bin/chromedriver"**

; node bin location = /usr/local/bin/node
; cwd = /home/test/opensearch_project/OpenSearch-Dashboards
; HOME = /home/test
; "npm config ls -l" to show all defaults.


Had to make changes in OpenSearch-Dashboards/test/functional/services/remote/webdriver.ts to take the path set in the env variable and it worked as shown below   

**//setChromeService(new chrome.ServiceBuilder(chromeDriver.path).enableVerboseLogging())
 .setChromeService(new chrome.ServiceBuilder(process.env.CHROMEDRIVER_FILEPATH).enableVerboseLogging())**
  
     

Any suggestions to make it working without making any changes in test file?

**Comment by Sunidhi-Gaonkar1** [comment]
Hi Team, any suggestions on above?
