### ISSUE TITLE
[BUG][UNIT TEST] EuiDataGrid does not render nested child component when use react testing-library

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#3393]
**Describe the bug**

When I try to add unit test for table vis (`table_vis_component.tsx`) using `@testing-library/react` , I found the `EuiDataGrid` can't render the complete DOM tree. Since `table_vis_component.tsx` has a relatively complex `EuiDataGrid` component, I searched other places which also used `EuiDataGrid`. There are three places and all of the them shows an incomplete DOM tree. Below is a DOM tree when test `inspector_data_grid.tsx`.

```
yarn test:jest src/plugins/vis_type_vega/public/vega_inspector/components/inspector_data_grid.test.tsx
yarn run v1.22.19
$ node scripts/jest src/plugins/vis_type_vega/public/vega_inspector/components/inspector_data_grid.test.tsx
  console.log
    <body>
      <div>
        <div
          data-eui="EuiFocusTrap"
        >
          <div
            class="euiDataGrid euiDataGrid--bordersAll euiDataGrid--headerShade euiDataGrid--footerOverline euiDataGrid--rowHoverHighlight euiDataGrid--stickyFooter"
          />
        </div>
      </div>
    </body>

      at debug (node_modules/@testing-library/react/dist/pure.js:109:13)

 PASS  src/plugins/vis_type_vega/public/vega_inspector/components/inspector_data_grid.test.tsx
  InspectorDataGrid
    ✓ should render (71 ms)

```

The test I created for `inspector_data_grid.tsx` is below. This is a simple debug test just to show the DOM tree. It is a good reference though to test any EUI/OUI/parent component.

```
import {render} from '@testing-library/react'
import { InspectorDataGrid } from './inspector_data_grid';
import React from 'react';

describe('InspectorDataGrid', function () {
    let props = {
        dataGridAriaLabel: 'test',
        columns: [],
        data: [],
    }
    it('should render', () => {
      const {debug} = render(<InspectorDataGrid {... props}/>);
      debug();
    })
});

```
**To Reproduce**
1. Copy the above example as `inspector_data_grid.test.tsx`
2. Run `yarn test:jest src/plugins/vis_type_vega/public/vega_inspector/components/inspector_data_grid.test.tsx`

**Expected behavior**
`@testing-library/react` render method should render a complete DOM tree. For example, let's construct a simple nested component below.

* First, create a parent app component

```
import React from 'react';
import { Sub } from './sub';

export class App extends React.Component {
  render() {
    return <Sub />;
  }
}
```

* Then add a sub-child component Sub

```
import React from 'react';
import { SubSub } from './subsub';

export class Sub extends React.Component {
  render() {
    return <SubSub />;
  }
}
```

* Then add a nested child component SubSub

```
import React from 'react';

export class SubSub extends React.Component {
  private timer: ReturnType<typeof setTimeout> | null = null;

  public renderSubSub() {
    if (this.timer !== null) {
      clearTimeout(this.timer);
    }
    this.timer = setTimeout(() => {
      console.log('do something');
    }, 1000);
    return 'sub sub';
  }

  render() {
    return <div>{this.renderSubSub()}</div>;
  }
}
```

* test if the sub child is rendered 

```
import React from 'react';
import { render} from '@testing-library/react';
import { App } from './app';

describe('My component', () => {
  test('that my component shows text', () => {
    const { getByText } = render(<App />);
    expect(getByText('sub sub')).toBeDefined();
  });
 test('the complete DOM tree', () => {
    const { debug } = render(<App />);
    debug();
  });
});

```

The result

```
$ node scripts/jest src/plugins/vis_type_table/public/components/test-folder/app.test.tsx
  console.log
    <body>
      <div>
        <div>
          sub sub
        </div>
      </div>
    </body>

      at debug (node_modules/@testing-library/react/dist/pure.js:109:13)

 PASS  src/plugins/vis_type_table/public/components/test-folder/app.test.tsx
  My component
    ✓ that my component shows text (20 ms)
    ✓ the complete DOM tree (14 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.254 s
Ran all test suites matching /src\/plugins\/vis_type_table\/public\/components\/test-folder\/app.test.tsx/i.
Done in 2.92s.
ubuntu@ip-172-3
```

From the above example, we could see that the nested child component should be rendered. We should be able to see a complete DOM tree.

**Additional context**

I also tested other EUI components. It looks to me, at least not all the EUI components have issue. Below is a test of `EuiAccordion` and the complete DOM tree is rendered.

```
yarn test:jest src/plugins/vis_builder/public/application/components/data_tab/field_selector.test.tsx
yarn run v1.22.19
$ node scripts/jest src/plugins/vis_builder/public/application/components/data_tab/field_selector.test.tsx
  console.log
    <body>
      <div>
        <div
          class="euiAccordion euiAccordion-isOpen vbFieldSelector__fieldGroup"
        >
          <div
            class="euiAccordion__triggerWrapper"
          >
            <button
              aria-controls="mockID"
              aria-expanded="true"
              class="euiAccordion__button"
              id="generated-id"
              type="button"
            >
              <span
                class="euiAccordion__iconWrapper"
              >
                <span
                  class="euiAccordion__icon euiAccordion__icon-isOpen"
                  data-euiicon-type="arrowRight"
                />
              </span>
              <span
                class="euiIEFlexWrapFix"
              >
                <span
                  class="euiTitle euiTitle--xxxsmall"
                >
                  mockHeader
                </span>
              </span>
            </button>
            <div
              class="euiAccordion__optionalAction"
            >
              <span
                class="euiNotificationBadge euiNotificationBadge--medium euiNotificationBadge--subdued"
              >
                4
              </span>
            </div>
          </div>
          <div
            aria-labelledby="generated-id"
            class="euiAccordion__childWrapper"
            id="mockID"
            role="region"
            tabindex="-1"
          >
            <div>
              <div
                class=""
              >
                <div
                  class="euiFlexItem"
                >
                  <div
                    class="euiPopover euiPopover--anchorRightUp euiPopover--displayBlock"
                    data-test-subj="field-popover"
                  >
                    <div
                      class="euiPopover__anchor"
                    >
                      <div
                        class="osdFieldButton vbFieldButton"
                        draggable="true"
                      >
                        <button
                          class="osd-resetFocusState osdFieldButton__button"
                          data-test-subj="field-bytes-showDetails"
                        >
                          <span
                            class="osdFieldButton__fieldIcon"
                          >
                            <span
                              class="euiToken euiToken--euiColorVis0 euiToken--square euiToken--light euiToken--large osdFieldIcon"
                            >
                              <span
                                aria-label="number"
                                data-euiicon-type="tokenNumber"
                                title="number"
                              />
                            </span>
                          </span>
                          <span
                            class="osdFieldButton__name"
                          >
                            <span
                              class="vbFieldButton__name"
                              data-test-subj="field-bytes"
                              title="bytes"
                            >
                              bytes
                            </span>
                          </span>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="euiFlexItem"
                >
                  <div
                    class="euiPopover euiPopover--anchorRightUp euiPopover--displayBlock"
                    data-test-subj="field-popover"
                  >
                    <div
                      class="euiPopover__anchor"
                    >
                      <div
                        class="osdFieldButton vbFieldButton"
                        draggable="true"
                      >
                        <button
                          class="osd-resetFocusState osdFieldButton__button"
                          data-test-subj="field-machine.ram-showDetails"
                        >
                          <span
                            class="osdFieldButton__fieldIcon"
                          >
                            <span
                              class="euiToken euiToken--euiColorVis0 euiToken--square euiToken--light euiToken--large osdFieldIcon"
                            >
                              <span
                                aria-label="number"
                                data-euiicon-type="tokenNumber"
                                title="number"
                              />
                            </span>
                          </span>
                          <span
                            class="osdFieldButton__name"
                          >
                            <span
                              class="vbFieldButton__name"
                              data-test-subj="field-machine.ram"
                              title="machine.ram"
                            >
                              machine.​ram
                            </span>
                          </span>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="euiFlexItem"
                >
                  <div
                    class="euiPopover euiPopover--anchorRightUp euiPopover--displayBlock"
                    data-test-subj="field-popover"
                  >
                    <div
                      class="euiPopover__anchor"
                    >
                      <div
                        class="osdFieldButton vbFieldButton"
                        draggable="true"
                      >
                        <button
                          class="osd-resetFocusState osdFieldButton__button"
                          data-test-subj="field-memory-showDetails"
                        >
                          <span
                            class="osdFieldButton__fieldIcon"
                          >
                            <span
                              class="euiToken euiToken--euiColorVis0 euiToken--square euiToken--light euiToken--large osdFieldIcon"
                            >
                              <span
                                aria-label="number"
                                data-euiicon-type="tokenNumber"
                                title="number"
                              />
                            </span>
                          </span>
                          <span
                            class="osdFieldButton__name"
                          >
                            <span
                              class="vbFieldButton__name"
                              data-test-subj="field-memory"
                              title="memory"
                            >
                              memory
                            </span>
                          </span>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
                <div
                  class="euiFlexItem"
                >
                  <div
                    class="euiPopover euiPopover--anchorRightUp euiPopover--displayBlock"
                    data-test-subj="field-popover"
                  >
                    <div
                      class="euiPopover__anchor"
                    >
                      <div
                        class="osdFieldButton vbFieldButton"
                        draggable="true"
                      >
                        <button
                          class="osd-resetFocusState osdFieldButton__button"
                          data-test-subj="field-phpmemory-showDetails"
                        >
                          <span
                            class="osdFieldButton__fieldIcon"
                          >
                            <span
                              class="euiToken euiToken--euiColorVis0 euiToken--square euiToken--light euiToken--large osdFieldIcon"
                            >
                              <span
                                aria-label="number"
                                data-euiicon-type="tokenNumber"
                                title="number"
                              />
                            </span>
                          </span>
                          <span
                            class="osdFieldButton__name"
                          >
                            <span
                              class="vbFieldButton__name"
                              data-test-subj="field-phpmemory"
                              title="phpmemory"
                            >
                              phpmemory
                            </span>
                          </span>
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </body>

      at debug (node_modules/@testing-library/react/dist/pure.js:109:13)

 PASS  src/plugins/vis_builder/public/application/components/data_tab/field_selector.test.tsx
  visBuilder sidebar field selector
    FieldGroup
      ✓ render the DOM tree (46 ms)

```

**Comment by seraphjiang** [comment]
Thank you for reporting this issue. This issue has been open for a long time without recent activity, and OpenSearch Dashboards has since moved to the 3.x release line (currently 3.6, with 3.7 upcoming). The last supported 2.x release is 2.19.x.

We're closing this as part of a housekeeping effort to keep the backlog actionable. If this issue is still reproducible on a supported version (2.19.x or 3.x), please feel free to reopen this issue or file a new one with updated reproduction steps and version details.

We appreciate your contribution to OpenSearch!
