### ISSUE TITLE
[BUG] PDF/PNG exports failure on "Failed to generate report: ProtocolError: Protocol error "

### ISSUE THREAD

**Issue by adriens** [opensearch-project/OpenSearch-Dashboards#3439]
# ?  Bug Description

- While trying to export a dashboard into portable formats (`PNG` or `PDF`), there is a failure.

# :footprints:  To Reproduce

1. Go to 'any dashboard'
2. Click on 'Export PNG or PDF'
3. Get the following stack 

```
Failed to generate report: ProtocolError: Protocol error (Target.setDiscoverTargets): Target closed. | type=log @timestamp=2023-02-17T04:14:40Z tags=["error","plugins","reportsDashboards"] pid=1

ProtocolError: Protocol error (Target.setDiscoverTargets): Target closed.
    at /usr/share/opensearch-dashboards/plugins/reportsDashboards/node_modules/puppeteer-core/src/common/Connection.ts:106:16
    at new Promise (<anonymous>)
    at Connection.send (/usr/share/opensearch-dashboards/plugins/reportsDashboards/node_modules/puppeteer-core/src/common/Connection.ts:102:12)
    at Function.create (/usr/share/opensearch-dashboards/plugins/reportsDashboards/node_modules/puppeteer-core/src/common/Browser.ts:231:22)
    at ChromeLauncher.launch (/usr/share/opensearch-dashboards/plugins/reportsDashboards/node_modules/puppeteer-core/src/node/Launcher.ts:179:31)
    at createVisualReport (/usr/share/opensearch-dashboards/plugins/reportsDashboards/server/routes/utils/visual_report/visualReportHelper.ts:68:19)
    at createReport (/usr/share/opensearch-dashboards/plugins/reportsDashboards/server/routes/lib/createReport.ts:93:30)
    at /usr/share/opensearch-dashboards/plugins/reportsDashboards/server/routes/report.ts:68:28
    at Router.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:163:44)
    at handler (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:124:50)
    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at Object.internals.handler (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)
    at Request._execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:281:9) {
  originalMessage: ''
} | type=log @timestamp=2023-02-17T04:14:40Z tags=["error","plugins","reportsDashboards"] pid=1

ERR Internal Server Error | type=error @timestamp=2023-02-17T04:14:40Z tags=[] pid=1 error={"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toError (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:143:19)\n    at HapiResponseAdapter.toHapiResponse (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:97:19)\n    at HapiResponseAdapter.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/response_adapter.js:92:17)\n    at Router.handle (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:164:34)\n    at handler (/usr/share/opensearch-dashboards/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/opensearch-dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)"} url=http://0.0.0.0:5601/api/reporting/generateReport?timezone=Pacific%2FNoumea&dateFormat=MMM+D%2C+YYYY+%40+HH%3Amm%3Ass.SSS&csvSeparator=%2C

POST /api/reporting/generateReport?timezone=Pacific%2FNoumea&dateFormat=MMM%20D%2C%20YYYY%20%40%20HH%3Amm%3Ass.SSS&csvSeparator=%2C 500 61ms - 9.0B | type=response @timestamp=2023-02-17T04:14:40Z tags=[] pid=1 method=post statusCode=500 req={"url":"/api/reporting/generateReport?timezone=Pacific%2FNoumea&dateFormat=MMM%20D%2C%20YYYY%20%40%20HH%3Amm%3Ass.SSS&csvSeparator=%2C","method":"post","headers":{"host":"0.0.0.0:5601","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0","accept":"*/*","accept-language":"en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7,zh-TW;q=0.6","accept-encoding":"gzip, deflate","referer":"http://0.0.0.0:5601/app/dashboards","content-type":"application/json","osd-xsrf":"reporting","pragma":"no-cache","content-length":"859","origin":"http://0.0.0.0:5601","connection":"keep-alive","securitytenant":""},"remoteAddress":"172.19.0.1","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0","referer":"http://0.0.0.0:5601/app/dashboards"} res={"statusCode":500,"responseTime":61,"contentLength":9}
```

# :dart: Expected behavior

- Should have got a pdf or image instead

# :1234:  Versions

On a docker (compose) env : 

- **OpenSearch** : `opensearchproject/opensearch:latest`
- **Dashboard** : `opensearchproject/opensearch-dashboards:latest`

# :heavy_plus_sign:  Plugins

- `N/A`

# :camera:  Screenshots

- We can drop you if it's needed.

**Comment by ashwin-pc** [comment]
Transfer issue to Reporting plugin @opensearch-project/transfer-request
