### ISSUE TITLE
[BUG]➤ Error: resize-observer-polyfill@npm:^1.5.1: No candidates found

### ISSUE THREAD

**Issue by pllizining** [opensearch-project/OpenSearch-Dashboards#3695]
yarn install  Report an error
Error message:

```
➤ YN0001: │ Error: resize-observer-polyfill@npm:^1.5.1: No candidates found
    at ge (C:\Users\ning\AppData\Local\node\corepack\yarn\3.5.0\yarn.js:439:7784)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
➤ YN0000: └ Completed in 52s 622ms
➤ YN0000: Failed with errors in 52s 632ms
```

Build failure

**Comment by Abyl10** [comment]
Hello, this is worked for me! The error message suggests that there were no compatible versions found for the "resize-observer-polyfill" package with a version constraint of "^1.5.1".

There are a few potential solutions you could try:
1. Update the version constraint in your package.json file to a compatible version of ```resize-observer-polyfill```.
2. Remove the version constraint for ```resize-observer-polyfill``` in your package.json file and run "yarn install" again to let Yarn install the latest compatible version of the package.
3. Clear your Yarn cache and try running ```yarn install``` again:
```bash
yarn cache clean
yarn install
```

If none of the above solutions work, you may want to check if there are any compatibility issues with other dependencies or if there are any issues with the registry you are using.

**Comment by pllizining** [comment]
> 您好，这对我有用！错误消息表明没有找到版本约束为“^1.5.1”的“resize-observer-polyfill”包的兼容版本。
> 
> 您可以尝试一些可能的解决方案：
> 
> 1. 将 package.json 文件中的版本约束更新为兼容的`resize-observer-polyfill`.
> 2. `resize-observer-polyfill`删除package.json 文件中的版本约束，然后再次运行“yarn install”，让 Yarn 安装包的最新兼容版本。
> 3. 清除 Yarn 缓存并`yarn install`再次尝试运行：
> 
> ```shell
> yarn cache clean
> yarn install
> ```
> 
> 如果上述解决方案均无效，您可能需要检查其他依赖项是否存在任何兼容性问题，或者您使用的注册表是否存在任何问题。

依然无法解决。
我尝试使用通git下载项目，依然会报这个错。
我尝试使用yarn osd bootstrap 这个命令
会报另一个错：Internal Error: opensearch-dashboards@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
但是我使用yarn install无法又会陷入这个循环。

**Comment by joshuarrrr** [comment]
For some historical context, see https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1252#discussion_r815208754 and https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1370#discussion_r835651026

@AMoo-Miki Can you weigh in here on proposed next steps?

**Comment by xiaodizi** [comment]
这个问题我解决了，我是个java开发，很少做npm相关的部署。也是尝试了很久。
1、需要用npm 全局安装 resize-observer-polyfill 
`npm install -g resize-observer-polyfill`

如果前期出现
`Internal Error: Cannot find module 'mkdirp'`
这个错误，也要全局安装 mkdirp。

2、安装 完 resize-observer-polyfill ，会有版本的提示，比如 
`$ npm install -g resize-observer-polyfill
+ resize-observer-polyfill@1.5.1
added 1 package from 1 contributor in 0.329s`
我这个就是 1.5.1 ，
然后需要在 yarn.lock 文件修改版本。我搜了一下，其他地方都是1.5.1 ，只有下边如图的地方是1.5.2
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/10411525/233936271-96d7355c-c947-4b6e-a808-36c1c43831ea.png">

修改了这些应该就可以正常进行yarn install了。如果还有其他问题，
也可以发出来，一起研究一下。

**Comment by bernardodesousa** [comment]
I am experiencing the same error trying `yarn install` in Ubuntu 20.04 on WSL. It's the first time I interact with yarn, so I'm a bit lost here. I followed the official instructions to install yarn with Node LTS, running `corepack enable` then `corepack prepare yarn@stable --activate`. Am I missing something?

**Comment by bernardodesousa** [comment]
I verified that this is not a problem with yarn nor with the resize-observer-polyfill package. I created a new yarn project and added the package to it. It got installed without a problem.

**Comment by AMoo-Miki** [comment]
`resize-observer-polyfill@^1.5.1` is marked to resolve to `@4lolo/resize-observer-polyfill@1.5.2` in tha lockfile.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/5ffb3d8f467e78c822209c4edbcc771c72cecca3/yarn.lock#L15320-L15322

Make sure you use `yarn bootstrap` for setting up the project (not `install`) and that the `yarn.lock` file is unmodified. Do not use `npm` as this project cannot be built with `npm`.

If you continue to have problems, please provide the output of each of these commands:
```
node -v
yarn -v
npm -v
```

**Comment by seraphjiang** [comment]
Thank you for reporting this issue. This issue has been open for a long time without recent activity, and OpenSearch Dashboards has since moved to the 3.x release line (currently 3.6, with 3.7 upcoming). The last supported 2.x release is 2.19.x.

We're closing this as part of a housekeeping effort to keep the backlog actionable. If this issue is still reproducible on a supported version (2.19.x or 3.x), please feel free to reopen this issue or file a new one with updated reproduction steps and version details.

We appreciate your contribution to OpenSearch!
