### ISSUE TITLE
yarn run test fails

### ISSUE THREAD

**Issue by designermonkey** [opensearch-project/OpenSearch-Dashboards#3923]
**Describe the bug**

Running `yarn run test` right after a fresh `yarn` fails:

```
yarn run test
yarn run v1.22.19
$ grunt test
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module '/my-path/opensearch-dashboards/node_modules/@osd/optimizer/target/index.js'. Please verify that the package.json has a valid "main" entry
Warning: Task "test" not found. Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
1. run `yarn`
2. run `yarn run test`

**Expected behavior**
I don't know as I have never run it before.

**Dashboards Version**
`main` branch

**Host/Environment (please complete the following information):**
 - OS: MacOS Ventura

**Additional context**

Looking into the `@osd` package, sure enough, there is no `target` folder.

**Comment by designermonkey** [comment]
`yarn run test:jest` causes similar output for the same missing file. I'm assuming others will do as well.

```
yarn run test:jest
yarn run v1.22.19
$ node scripts/jest
Error: Cannot find module '/Users/porterj/Projects/opensearch-dashboards/node_modules/@osd/optimizer/target/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Module.Hook._require.Module.require (/Users/porterj/Projects/opensearch-dashboards/node_modules/require-in-the-middle/index.js:61:29)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/porterj/Projects/opensearch-dashboards/src/setup_node_env/index.js:32:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by manasvinibs** [comment]
Hi @designermonkey 
Thanks for reaching out to us! Did you try bootstrap before running yarn test?
Please follow the below linked developer guide to get Opensearch Dashboard up and running -
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#bootstrap-opensearch-dashboards. 
Also, `yarn run test:jest` looks correct but we don't run `yarn run test` in general.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/TESTING.md

**Comment by ashwin-pc** [comment]
Closing the issue for now. Feel free to reopen if you still face some issues here.
