### ISSUE TITLE
[BUG] Downloading geckodriver error

### ISSUE THREAD

**Issue by xiaodizi** [opensearch-project/OpenSearch-Dashboards#3926]
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/10411525/233962755-1e69f720-49db-4066-bcfe-d2e8a9a9ff9d.png">

I cloned the latest code from the master branch, but when running yarn install, the above error occurred. I also tried to install geckodriver on the local machine, but it still downloaded. I also tried to change the baseCDNURL download address in the index.js file in the geckodriver folder in the node_modules folder to the local file:// path. But there is still no solution.

I need help. I don't know why

**Comment by ananzh** [comment]
Could you try `yarn osd clean` then yarn osd bootstrap` and let me know the result?

**Comment by ananzh** [comment]
If the above cmds not working, and you see `"Unhandled 'error' event socket hang up"` error message again, it could be several causes

* Check your internet connection and make sure you have a stable internet connection. Let's try to download it directly with curl cmd. If you are using mac, you could try this:
```
curl -LO https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-macos.tar.gz
```

*  If you are using a proxy server, make sure you have correctly configured your proxy settings. 
*  Disable the firewall or antivirus temporarily.

See whether these could provide us more info about the connection.

**Comment by kavilla** [comment]
One thing to note is that GitHub was experiencing outages yesterday and could have caused this failure in downloading.

Incident page: https://isdown.app/integrations/github/incidents/191387-incident-with-copilot

Are downloads still failing?

**Comment by xiaodizi** [comment]
> If the above cmds not working, and you see `"Unhandled 'error' event socket hang up"` error message again, it could be several causes
> 
> * Check your internet connection and make sure you have a stable internet connection. Let's try to download it directly with curl cmd. If you are using mac, you could try this:
> 
> ```
> curl -LO https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-macos.tar.gz
> ```
> 
> * If you are using a proxy server, make sure you have correctly configured your proxy settings.
> * Disable the firewall or antivirus temporarily.
> 
> See whether these could provide us more info about the connection.

I downloaded the package geckodriver-v0.330-macos.tar.gz separately, but how do I get the source code to use my local package instead of downloading it? I am a Chinese programmer, the Internet problem has been bothering me for a long time, still have not solved this problem.

`# lei.fu @ MacBook-Pro-2 in ~/java/mca/OpenSearch-Dashboards on git:main x [9:23:59] 
$ yarn osd bootstrap
yarn run v1.22.10
$ scripts/use_node scripts/osd bootstrap
 info [opensearch-dashboards] running yarn

$ scripts/use_node ./preinstall_check
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.5.2"
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-63515c9a-f8d5-40d3-8268-8082a578d456 > osd_tp_run_pipeline > @elastic/eui@1.1.1" has incorrect peer dependency "typescript@^4.0.5".
warning " > http-aws-es@6.0.0" has unmet peer dependency "aws-sdk@^2.138.0".
warning " > http-aws-es@6.0.0" has incorrect peer dependency "elasticsearch@^15.0.0".
[4/4] 🔨  Building fresh packages...
[-/18] ⢀ waiting...
[-/18] ⢀ waiting...
[-/18] ⢀ waiting...
[-/18] ⢀ waiting...
error /Users/lei.fu/java/mca/OpenSearch-Dashboards/node_modules/geckodriver: Command failed.
Exit code: 1
Command: node index.js
Arguments: 
Directory: /Users/lei.fu/java/mca/OpenSearch-Dashboards/node_modules/geckodriver
Output:
Downloading geckodriver... events.js:377
      throw er; // Unhandled 'error' event
      ^

RequestError: connect ETIMEDOUT 185.199.110.133:443
    at ClientRequest.<anonymous> (/Users/lei.fu/java/mca/OpenSearch-Dashboards/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/Users/lei.fu/java/mca/OpenSearch-Dashboards/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Emitted 'error' event on Request instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1682472314216,
    socket: 1682472314216,
    lookup: 1682472314217,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1682472389074,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 74858




ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: /Users/lei.fu/.cache/node/corepack/yarn/1.22.10/bin/yarn.js install --non-interactive
          at makeError (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:25045:11)
          at handlePromise (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:23981:26)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async installInDir (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:23704:3)
          at async Project.installDependencies (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:15168:5)
          at async Object.run (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:9188:11)
          at async runCommand (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:56360:5)
          at async Object.run (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:278:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by xiaodizi** [comment]
> If the above cmds not working, and you see `"Unhandled 'error' event socket hang up"` error message again, it could be several causes
> 
> * Check your internet connection and make sure you have a stable internet connection. Let's try to download it directly with curl cmd. If you are using mac, you could try this:
> 
> ```
> curl -LO https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-macos.tar.gz
> ```
> 
> * If you are using a proxy server, make sure you have correctly configured your proxy settings.
> * Disable the firewall or antivirus temporarily.
> 
> See whether these could provide us more info about the connection.

I downloaded the package geckodriver-v0.330-macos.tar.gz separately, but how do I get the source code to use my local package instead of downloading it? I am a Chinese programmer, the Internet problem has been bothering me for a long time, still have not solved this problem.

`# lei.fu @ MacBook-Pro-2 in ~/java/mca/OpenSearch-Dashboards on git:main x [9:23:59] 
$ yarn osd bootstrap
yarn run v1.22.10
$ scripts/use_node scripts/osd bootstrap
 info [opensearch-dashboards] running yarn

$ scripts/use_node ./preinstall_check
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.5.2"
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-63515c9a-f8d5-40d3-8268-8082a578d456 > osd_tp_run_pipeline > @elastic/eui@1.1.1" has incorrect peer dependency "typescript@^4.0.5".
warning " > http-aws-es@6.0.0" has unmet peer dependency "aws-sdk@^2.138.0".
warning " > http-aws-es@6.0.0" has incorrect peer dependency "elasticsearch@^15.0.0".
[4/4] 🔨  Building fresh packages...
[-/18] ⢀ waiting...
[-/18] ⢀ waiting...
[-/18] ⢀ waiting...
[-/18] ⢀ waiting...
error /Users/lei.fu/java/mca/OpenSearch-Dashboards/node_modules/geckodriver: Command failed.
Exit code: 1
Command: node index.js
Arguments: 
Directory: /Users/lei.fu/java/mca/OpenSearch-Dashboards/node_modules/geckodriver
Output:
Downloading geckodriver... events.js:377
      throw er; // Unhandled 'error' event
      ^

RequestError: connect ETIMEDOUT 185.199.110.133:443
    at ClientRequest.<anonymous> (/Users/lei.fu/java/mca/OpenSearch-Dashboards/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/Users/lei.fu/java/mca/OpenSearch-Dashboards/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Emitted 'error' event on Request instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ETIMEDOUT',
  timings: {
    start: 1682472314216,
    socket: 1682472314216,
    lookup: 1682472314217,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1682472389074,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 74858




ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: /Users/lei.fu/.cache/node/corepack/yarn/1.22.10/bin/yarn.js install --non-interactive
          at makeError (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:25045:11)
          at handlePromise (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:23981:26)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at async installInDir (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:23704:3)
          at async Project.installDependencies (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:15168:5)
          at async Object.run (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:9188:11)
          at async runCommand (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:56360:5)
          at async Object.run (/Users/lei.fu/java/mca/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:278:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by xiaodizi** [comment]
> One thing to note is that GitHub was experiencing outages yesterday and could have caused this failure in downloading.
> 
> Incident page: https://isdown.app/integrations/github/incidents/191387-incident-with-copilot
> 
> Are downloads still failing?

Yes, it's still a failure.

**Comment by xiaodizi** [comment]
Sorry, I accidentally closed this question.

**Comment by xiaodizi** [comment]
close

**Comment by manasvinibs** [comment]
Closing this as the issue seems to be resolved.
