### ISSUE TITLE
[MD] Data source client error handling

### ISSUE THREAD

**Issue by kristenTian** [opensearch-project/OpenSearch-Dashboards#4278]
When install sample data source, the existing behavior is try to delete the existing sample index for clean up. (Given there are more categories to determine if sample data is installed ). 

The existing code will try catch the error and ignore given it's not a real error case.  see: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2322c53d10664d68c7d2ee21a86a4e29d1919d9c/src/plugins/home/server/services/sample_data/routes/install.ts#L126-L132
However for data source use case, the error will still be thrown out:

```
server    log   [19:14:58.425] [error][data-source-service][dataSource][legacy][plugins] Failed to get data source client for dataSourceId: [ab9c3560-0893-11ee-b470-6bd66995313a]. [index_not_found_exception] no such index [opensearch_dashboards_sample_data_flights], with { index="opensearch_dashboards_sample_data_flights" & resource.id="opensearch_dashboards_sample_data_flights" & resource.type="index_or_alias" & index_uuid="_na_" } :: {"path":"/opensearch_dashboards_sample_data_flights","query":{},"statusCode":404,"response":"{\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index [opensearch_dashboards_sample_data_flights]\",\"index\":\"opensearch_dashboards_sample_data_flights\",\"resource.id\":\"opensearch_dashboards_sample_data_flights\",\"resource.type\":\"index_or_alias\",\"index_uuid\":\"_na_\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index [opensearch_dashboards_sample_data_flights]\",\"index\":\"opensearch_dashboards_sample_data_flights\",\"resource.id\":\"opensearch_dashboards_sample_data_flights\",\"resource.type\":\"index_or_alias\",\"index_uuid\":\"_na_\"},\"status\":404}"}: Error: [index_not_found_exception] no such index [opensearch_dashboards_sample_data_flights], with { index="opensearch_dashboards_sample_data_flights" & resource.id="opensearch_dashboards_sample_data_flights" & resource.type="index_or_alias" & index_uuid="_na_" }
    at respond (/Users/tyarong/repository/OpenSearch-Dashboards/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/Users/tyarong/repository/OpenSearch-Dashboards/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/Users/tyarong/repository/OpenSearch-Dashboards/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/Users/tyarong/repository/OpenSearch-Dashboards/node_modules/lodash/lodash.js:4991:19)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by HarshPanchal26** [comment]
Hey I am interested to solve this , Can you assign it to me ?

**Comment by zhongnansu** [comment]
@kristenTian Hi Kristan, is this being resolved, can we close?
