### ISSUE TITLE
[Flakey Test] Run functional tests on Linux (ciGroup9)

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#4422]
**Describe the bug**

Run functional tests on Linux (ciGroup9) fails frequently

```
     │1)    visualize app
     │       
     │         area charts
     │           date histogram when no time filter
     │             interval errors
     │               should show error when calendar interval invalid:
     │
     │      WebDriverError: unknown error: unhandled inspector error: {"code":-32000,"message":"No node with given id found"}
     │   (Session info: headless chrome=114.0.5735.133)
     │       at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:550:15)
     │       at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:565:13)
     │       at Executor.execute (node_modules/selenium-webdriver/lib/http.js:491:26)
     │       at processTicksAndRejections (node:internal/process/task_queues:95:5)
     │       at Task.exec (test/functional/services/remote/prevent_parallel_calls.ts:51:22)
```

**To Reproduce**
1. Go to https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/5396315142/jobs/9799811258#step:15:426

**Expected behavior**
Should not flake

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by ashwin-pc** [comment]
Another example run https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/5383797836/jobs/9771391333?pr=4404

**Comment by ashwin-pc** [comment]
Another example: https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/5407091966/jobs/9824696185?pr=4436

**Comment by ashwin-pc** [comment]
@ananzh this is a nice find. Let me try making that change and tracking to see if it reduces our CI failures :)
