### ISSUE TITLE
[BUG] Using latest yarn is causing issues in osd bootstrap

### ISSUE THREAD

**Issue by vamsi-amazon** [opensearch-project/OpenSearch-Dashboards#4452]
**Describe the bug**
I was following the developer guide [here](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md) which says to install latest yarn version.

I have installed Yarn version 3.6.0, but I encountered issues with bootstrapping using this version. After struggling for a while, I found success after switching to an older version 1.22.10.

Error details with yarn 3.6.0
```
Internal Error: opensearch-dashboards@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/Users/reddyvam/.cache/node/corepack/yarn/3.6.0/yarn.js:435:5145)
    at kf.getCandidates (/Users/reddyvam/.cache/node/corepack/yarn/3.6.0/yarn.js:391:1264)
    at /Users/reddyvam/.cache/node/corepack/yarn/3.6.0/yarn.js:439:8033
    at df (/Users/reddyvam/.cache/node/corepack/yarn/3.6.0/yarn.js:390:11070)
    at ge (/Users/reddyvam/.cache/node/corepack/yarn/3.6.0/yarn.js:439:8013)
    at async Promise.allSettled (index 0)
    at async io (/Users/reddyvam/.cache/node/corepack/yarn/3.6.0/yarn.js:390:10398)
    at async /Users/reddyvam/.cache/node/corepack/yarn/3.6.0/yarn.js:439:8545
    at async ti.startProgressPromise (/Users/reddyvam/.cache/node/corepack/yarn/3.6.0/yarn.js:390:47579)
    at async je.resolveEverything (/Users/reddyvam/.cache/node/corepack/yarn/3.6.0/yarn.js:439:6573)
```

We either need to update the documentation with prescribed version or fix the bug.

**To Reproduce**
1. Follow [developer guider](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md) here and install latest version of yarn.
2. Run yarn osd bootstrap
3. See error

**Expected behavior**
Bootstrapping should be successful.

**OpenSearch Version**
3.0.0

**Dashboards Version**
3.0.0

**Host/Environment (please complete the following information):**
 - OS: M1 mac

**Comment by wbeckler** [comment]
Nice catch! Feel free to PR a fix to the developer guide.

**Comment by bagipriyank** [comment]
this is still an issue. do we at least know what version of yarn will work?

**Comment by vamsi-amazon** [comment]
@bagipriyank  1.22.10 worked for me.

**Comment by bagipriyank** [comment]
I am running into this error with 1.22.10 
```
 yarn opensearch snapshot
yarn run v1.22.10
$ scripts/use_node scripts/opensearch snapshot
 info Installing from snapshot
   │ info version: 3.0.0
   │ info install path: /Users/pbagrecha/dea/OpenSearch-Dashboards/.opensearch/3.0.0
   │ info license: oss
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-SNAPSHOT/opensearch-min-3.0.0-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Daily general-availability snapshot URL not found for current version, falling back to release-candidate snapshot URL.
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc5/opensearch-3.0.0-rc5-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc4/opensearch-3.0.0-rc4-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc3/opensearch-3.0.0-rc3-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc2/opensearch-3.0.0-rc2-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc1/opensearch-3.0.0-rc1-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ info Verifying snapshot URL at https://artifacts.opensearch.org/snapshots/core/opensearch/3.0.0-rc0/opensearch-3.0.0-rc0-SNAPSHOT-darwin-arm64-latest.tar.gz
   │ERROR Snapshots for 3.0.0 are not available
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bagipriyank** [comment]
I ended up running opensearch via docker and running opensearch-dashboards via yarn for developing a custom plugin. I tried `yarn opensearch source` as well as `yarn opensearch tar` but none of them worked.

**Comment by seraphjiang** [comment]
Thank you for reporting this issue. This issue has been open for a long time without recent activity, and OpenSearch Dashboards has since moved to the 3.x release line (currently 3.6, with 3.7 upcoming). The last supported 2.x release is 2.19.x.

We're closing this as part of a housekeeping effort to keep the backlog actionable. If this issue is still reproducible on a supported version (2.19.x or 3.x), please feel free to reopen this issue or file a new one with updated reproduction steps and version details.

We appreciate your contribution to OpenSearch!
