### ISSUE TITLE
[PLUGINS] plugins server cant fetch data

### ISSUE THREAD

**Issue by ReeseLiu2021** [opensearch-project/OpenSearch-Dashboards#4600]
**Describe**

I want to get external data in one plugin and then provide it to another plugin, thus realizing data sharing in the plugin. But when I get the data, the request reports the following error:

```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred."
}
```

```json
server   error  [09:46:25.811]  Error: Internal Server Error
    at HapiResponseAdapter.toInternalError (/home/git/OpenSearch-Dashboards-Plugins/OpenSearch-Dashboards/src/core/server/http/router/response_adapter.ts:71:19)
    at Router.handle (/home/git/OpenSearch-Dashboards-Plugins/OpenSearch-Dashboards/src/core/server/http/router/router.ts:304:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at handler (/home/git/OpenSearch-Dashboards-Plugins/OpenSearch-Dashboards/src/core/server/http/router/router.ts:241:11)
    at exports.Manager.execute (/home/git/OpenSearch-Dashboards-Plugins/OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at Object.internals.handler (/home/git/OpenSearch-Dashboards-Plugins/OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/home/git/OpenSearch-Dashboards-Plugins/OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/home/git/OpenSearch-Dashboards-Plugins/OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)
    at Request._execute (/home/git/OpenSearch-Dashboards-Plugins/OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)
```

**To Reproduce**

```js
import { IRouter } from '../../../../src/core/server';
import axios from "axios";

export function defineRoutes(router: IRouter) {
  router.get(
    {
      path: '/api/test2/example',
      validate: false,
    },

    async (context, request, response) => {
      const data = await axios.get('https://fakestoreapi.com/products/1')
      return response.ok({
        body: {
          time: data
        },
      });
    }
  );
}
```

**Expected behavior**
How to correctly fetch external data, or how to implement sharing externally fetched data in different plugins

**OpenSearch Version**
v2.8.0

**Dashboards Version**
v2.8.0

**Comment by AMoo-Miki** [comment]
I have a feeling that the problem is with `data`. What `axios.get` returns is a response object which more than likely has cyclic references or unserializable properties.

To quickly verify that make this change:
```js
const { data } = await axios.get('https://fakestoreapi.com/products/1');
```

**Comment by ReeseLiu2021** [comment]
> I have a feeling that the problem is with `data`. What `axios.get` returns is a response object which more than likely has cyclic references or unserializable properties.
> 
> To quickly verify that make this change:
> 
> ```js
> const { data } = await axios.get('https://fakestoreapi.com/products/1');
> ```

Thanks! ```data``` is the problem
