### ISSUE TITLE
[BUG] Opensearch dashboards doesn't work with management disabled

### ISSUE THREAD

**Issue by lde-avaleo** [opensearch-project/OpenSearch-Dashboards#4642]
**Describe the bug**
Opensearch dashboards doesn't work with management disabled.
There's an error after opening opensearch-dashboards in a browser:

```
Version: 2.9.0
Build: 6391
Error: No trigger [triggerId = SAVED_OBJECT_DELETE_TRIGGER] exists, for attaching action [actionId = SAVED_OBJECT_DELETE_ACTION].
    at UiActionsService.attachAction (http://localhost:5601/6391/bundles/plugin/uiActions/uiActions.plugin.js:1:66816)
    at UiActionsService.addTriggerAction (http://localhost:5601/6391/bundles/plugin/uiActions/uiActions.plugin.js:1:67733)
    at bootstrapUiActions (http://localhost:5601/6391/bundles/plugin/visAugmenter/visAugmenter.plugin.js:1:187522)
    at VisAugmenterPlugin.start (http://localhost:5601/6391/bundles/plugin/visAugmenter/visAugmenter.plugin.js:1:189345)
    at PluginWrapper._callee2$ (http://localhost:5601/6391/bundles/core/core.entry.js:15:667501)
    at tryCatch (http://localhost:5601/6391/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910)
    at Generator.invoke [as _invoke] (http://localhost:5601/6391/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790926)
    at Generator.next (http://localhost:5601/6391/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105)
    at plugin_asyncGeneratorStep (http://localhost:5601/6391/bundles/core/core.entry.js:15:664102)
    at _next (http://localhost:5601/6391/bundles/core/core.entry.js:15:664419)
```

**To Reproduce**
Download opensearch-dashboard 2.9.0. Add to opensearch-dashboards.yml property:
```
management.enabled: false
```
Start server. Try open it in a browser

**Expected behavior**
I can use opensearch-dashboards without management

**OpenSearch Version**
2.9.0

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**
Not relevant

**Host/Environment (please complete the following information):**
Not relevant

**Comment by AMoo-Miki** [comment]
Thanks for reporting this. I have been able to reproduce the issue and know why it is happening.

**Comment by joshuarrrr** [comment]
@ashwin-pc This can be closed via https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4891, right?

**Comment by kavilla** [comment]
Yes fixed. Follow up issue made for adding functional tests.
