### ISSUE TITLE
Error on Build opensearch-dashboard

### ISSUE THREAD

**Issue by saeed-mcu** [opensearch-project/OpenSearch-Dashboards#4801]
I try to build opensearch-dashboard on Ubuntu 22.04.2 LTS.
I did step by step based on [documentation](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#opensearch-dashboards-developer-guide)
```bash
$ nvm install 18.16.0
$ nvm use 18.16.0
$ corepack prepare yarn@3.6.2 --activate
```
My first error was :
```bash
$ yarn osd bootstrap
Internal Error: opensearch-dashboards@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/root/.cache/node/corepack/yarn/3.6.2/yarn.js:435:5145)
    at kf.getCandidates (/root/.cache/node/corepack/yarn/3.6.2/yarn.js:391:1264)
    at /root/.cache/node/corepack/yarn/3.6.2/yarn.js:439:8033
    at df (/root/.cache/node/corepack/yarn/3.6.2/yarn.js:390:11070)
    at ge (/root/.cache/node/corepack/yarn/3.6.2/yarn.js:439:8013)
    at async Promise.allSettled (index 0)
    at async io (/root/.cache/node/corepack/yarn/3.6.2/yarn.js:390:10398)
    at async /root/.cache/node/corepack/yarn/3.6.2/yarn.js:439:8545
    at async ti.startProgressPromise (/root/.cache/node/corepack/yarn/3.6.2/yarn.js:390:47579)
    at async je.resolveEverything (/root/.cache/node/corepack/yarn/3.6.2/yarn.js:439:6573)
```
So, I run the following command but encountered error :
```
...

➤ YN0001: │ Error: resize-observer-polyfill@npm:^1.5.1: No candidates found
    at ge (/root/.cache/node/corepack/yarn/3.6.2/yarn.js:439:8124)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 309)
    at async io (/root/.cache/node/corepack/yarn/3.6.2/yarn.js:390:10398)
➤ YN0000: └ Completed in 6m 24s
➤ YN0000: Failed with errors in 6m 24s
```
How can I fix the error and build the project ?

**Comment by ashwin-pc** [comment]
@saeed-mcu can you try `npm -i -g yarn` instead of `corepack prepare yarn@3.6.2 --activate`?

**Comment by evankielley** [comment]
I had this issue too. I fixed it by downgrading yarn to "classic" version 1.22.19.

**Comment by saeed-mcu** [comment]
thanks @evankielley  and @ashwin-pc for your reply.

I have changed yarn and  node version :
```
$  node -v
v18.17.1
$ npm -v
9.6.7
$ yarn -v
1.22.19
```
But my error has changed as following : 
```
yarn osd bootstrap
yarn run v1.22.19
$ scripts/use_node scripts/osd bootstrap
 info [opensearch-dashboards] running yarn

$ scripts/use_node ./preinstall_check
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.

 succ yarn.lock analysis completed without any issues
 succ 2 bootstrap builds are cached
 info [@osd/cross-platform] running [osd:bootstrap] script
 info [@osd/stylelint-plugin-stylelint] running [osd:bootstrap] script
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: /usr/local/lib/node_modules/yarn/bin/yarn.js run osd:bootstrap
      /root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:84772
                      throw e;
                      ^

      TypeError: Cannot read properties of undefined (reading 'length')
          at getPropertyOfType (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:42959:45)
          at getExternalModuleMember (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36286:46)
          at getTargetOfImportSpecifier (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36369:28)
          at getTargetOfAliasDeclaration (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36427:28)
          at resolveAlias (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36462:30)
          at tryResolveAlias (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36478:24)
          at getCandidateName (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:54471:33)
          at Object.getSpellingSuggestion (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:1521:33)
          at getSpellingSuggestionForName (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:54461:23)
          at /root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:54422:34

      Node.js v18.17.1
      error Command failed with exit code 1.
      error Command failed with exit code 1.
      $ yarn build
      $ tsc
      info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
      info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
          at makeError (/root/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:26834:11)
          at handlePromise (/root/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:25770:26)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async /root/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:9251:11
          at async scheduleItem (/root/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:11319:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by evankielley** [comment]
Hmm do you get the same error if you run `yarn cache clean` first?

**Comment by saeed-mcu** [comment]
@evankielley 
After run `yarn cache clean` nothing changed and I get the same error.

**Comment by ashwin-pc** [comment]
Did you also try running `yarn osd clean`? If bootstrap ever fails for me, I usually run this to make sure that the repo is in a clean state before installing any dependencies.

**Comment by DaCastle** [comment]
> But my error has changed as following :
> 
> ```
> yarn osd bootstrap
> yarn run v1.22.19
> $ scripts/use_node scripts/osd bootstrap
>  info [opensearch-dashboards] running yarn
> 
> $ scripts/use_node ./preinstall_check
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> success Already up-to-date.
> 
>  succ yarn.lock analysis completed without any issues
>  succ 2 bootstrap builds are cached
>  info [@osd/cross-platform] running [osd:bootstrap] script
>  info [@osd/stylelint-plugin-stylelint] running [osd:bootstrap] script
> ERROR [bootstrap] failed:
> ERROR Error: Command failed with exit code 1: /usr/local/lib/node_modules/yarn/bin/yarn.js run osd:bootstrap
>       /root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:84772
>                       throw e;
>                       ^
> 
>       TypeError: Cannot read properties of undefined (reading 'length')
>           at getPropertyOfType (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:42959:45)
>           at getExternalModuleMember (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36286:46)
>           at getTargetOfImportSpecifier (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36369:28)
>           at getTargetOfAliasDeclaration (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36427:28)
>           at resolveAlias (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36462:30)
>           at tryResolveAlias (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:36478:24)
>           at getCandidateName (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:54471:33)
>           at Object.getSpellingSuggestion (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:1521:33)
>           at getSpellingSuggestionForName (/root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:54461:23)
>           at /root/OpenSearch-Dashboards/node_modules/typescript/lib/tsc.js:54422:34
> 
>       Node.js v18.17.1
>       error Command failed with exit code 1.
>       error Command failed with exit code 1.
>       $ yarn build
>       $ tsc
>       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>           at makeError (/root/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:26834:11)
>           at handlePromise (/root/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:25770:26)
>           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>           at async /root/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:9251:11
>           at async scheduleItem (/root/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:11319:9)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

I'm encountering this same error - I've tried yarn osd clean with numerous different node versions, have not found a way around this in a few hours of clearing/re-building node_modules via yarn osd bootstrap. Here's my output my variation having a reference to an incompatible typescript version:

```
$ yarn osd bootstrap
yarn run v1.22.19
$ scripts/use_node scripts/osd bootstrap
 info [opensearch-dashboards] running yarn

$ scripts/use_node ./preinstall_check
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@5.4.2"
success Already up-to-date.
$ scripts/use_node scripts/postinstall
Patching node_modules/font-awesome/scss/_variables.scss
Patching node_modules/@elastic/charts/dist/theme.scss
Patching node_modules/rison-node/js/rison.js

 info [opensearch-security-dashboards] running yarn

[1/4] Resolving packages...
success Already up-to-date.

 succ yarn.lock analysis completed without any issues
 warn yarn.lock file is out of date, please run `yarn osd bootstrap` to re-enable caching
 succ 2 bootstrap builds are cached
 info [@osd/cross-platform] running [osd:bootstrap] script
 info [@osd/stylelint-plugin-stylelint] running [osd:bootstrap] script
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: C:\Users\DakotaCastleberg\AppData\Local\node\corepack\v1\yarn\1.22.19\bin\yarn.js run osd:bootstrap        
      C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:84772
                      throw e;
                      ^

      TypeError: Cannot read properties of undefined (reading 'length')
          at getPropertyOfType (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:42959:45)
          at getExternalModuleMember (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:36286:46)    
          at getTargetOfImportSpecifier (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:36369:28) 
          at getTargetOfAliasDeclaration (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:36427:28)
          at resolveAlias (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:36462:30)
          at tryResolveAlias (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:36478:24)
          at getCandidateName (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:54471:33)
          at Object.getSpellingSuggestion (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:1521:33)
          at getSpellingSuggestionForName (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:54461:23)
          at C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\node_modules\typescript\lib\tsc.js:54422:34

      Node.js v18.20.2
      error Command failed with exit code 1.
      error Command failed with exit code 1.
      $ yarn build
      $ tsc
      info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
      info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
          at makeError (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:27356:11)
          at handlePromise (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:26292:26)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:9145:11
          at async scheduleItem (C:\Users\DakotaCastleberg\Documents\Projects\OpenSearch-Dashboards\packages\osd-pm\dist\index.js:11198:9)
Done in 14.17s. 
```

**Comment by hufozhuan** [comment]
Encountering the same error, I have been unable to solve this problem. 

 succ yarn.lock analysis completed without any issues
 warn yarn.lock file is out of date, please run `yarn osd bootstrap` to re-enable caching
 info [@osd/cross-platform] running [osd:bootstrap] script
 info [@osd/stylelint-plugin-stylelint] running [osd:bootstrap] script
 info [@osd/test-subj-selector] running [osd:bootstrap] script
 info [@osd/utility-types] running [osd:bootstrap] script
ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 1: /usr/local/share/.config/yarn/global/node_modules/yarn/bin/yarn.js run osd:bootstrap
      /app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:84772
                      throw e;
                      ^

      TypeError: Cannot read properties of undefined (reading 'length')
          at getPropertyOfType (/app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:42959:45)
          at getExternalModuleMember (/app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:36286:46)
          at getTargetOfImportSpecifier (/app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:36369:28)
          at getTargetOfAliasDeclaration (/app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:36427:28)
          at resolveAlias (/app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:36462:30)
          at tryResolveAlias (/app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:36478:24)
          at getCandidateName (/app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:54471:33)
          at Object.getSpellingSuggestion (/app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:1521:33)
          at getSpellingSuggestionForName (/app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:54461:23)
          at /app/udb-sx-dashboards/node_modules/typescript/lib/tsc.js:54422:34

      Node.js v18.19.0
      error Command failed with exit code 1.
      error Command failed with exit code 1.
      $ yarn build
      $ tsc
      info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
      info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
          at makeError (/app/udb-sx-dashboards/packages/osd-pm/dist/index.js:27391:11)
          at handlePromise (/app/udb-sx-dashboards/packages/osd-pm/dist/index.js:26327:26)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
          at async /app/udb-sx-dashboards/packages/osd-pm/dist/index.js:9145:11
          at async scheduleItem (/app/udb-sx-dashboards/packages/osd-pm/dist/index.js:11198:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ashwin-pc** [comment]
Can you provide some more details on how I can reproduce this @hufozhuan ?
