### ISSUE TITLE
[PURIFY] Fix broken / transient integration and functional test cases 

### ISSUE THREAD

**Issue by mihirsoni** [opensearch-project/OpenSearch-Dashboards#5]
- [ ] copies files and directories from source to dest, creating dest if necessary, respecting mode (fs.test.ts) ?
- [ ] address TODO integration tests
- [ ] address skipped integration tests
- [ ] address inconsistent functional tests

**Comment by kavilla** [comment]
There a couple of functional tests that fail locally but pass on the CI. This is an error on how the test was built and need to be improved. For example, a dirty data state where in the upstream they completely clear out everything where in our fork we don't clear it out.

Here are the current failures locally:

```
         │4 failing
         │
         │1)    management
         │       
         │         index pattern empty view
         │           shows empty views:
         │
         │      Error: expected testSubject(createAnyway) to exist
         │       at TestSubjects.existOrFail (test/functional/services/common/test_subjects.ts:75:15)
         │ 
         │ 
         │2)    management
         │       
         │         index pattern empty view
         │           "after all" hook for "doesn't show read-only badge":
         │
         │      Error: [index_not_found_exception] no such index [logstash-a], with { index="logstash-a" & resource.id="logstash-a" & resource.type="index_or_alias" & index_uuid="_na_" }
         │       at respond (node_modules/elasticsearch/src/lib/transport.js:349:15)
         │       at checkRespForFailure (node_modules/elasticsearch/src/lib/transport.js:306:7)
         │       at HttpConnector.<anonymous> (node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
         │       at IncomingMessage.wrapper (node_modules/lodash/lodash.js:4949:19)
         │       at endReadableNT (_stream_readable.js:1145:12)
         │       at process._tickCallback (internal/process/next_tick.js:63:19)
         │ 
         │ 
         │3)    management
         │       
         │         index pattern filter
         │           should filter indexed fields:
         │
         │      TimeoutError: Waiting for element to be located By(xpath, //a[descendant::*[text()='logstash-*']])
         │ Wait timed out after 10047ms
         │       at /home/avillk/repos/OpenSearch-Dashboards/node_modules/selenium-webdriver/lib/webdriver.js:842:17
         │       at process._tickCallback (internal/process/next_tick.js:68:7)
         │ 
         │ 
         │4)    management
         │       
         │         index pattern filter
         │           "after each" hook for "should filter indexed fields":
         │
         │      retry.try timeout: Error: retry.try timeout: TimeoutError: Waiting for element to be located By(css selector, [data-test-subj="deleteIndexPatternButton"])
         │ Wait timed out after 10025ms
         │     at /home/avillk/repos/OpenSearch-Dashboards/node_modules/selenium-webdriver/lib/webdriver.js:842:17
         │     at process._tickCallback (internal/process/next_tick.js:68:7)
         │     at onFailure (/home/avillk/repos/OpenSearch-Dashboards/test/common/services/retry/retry_for_success.ts:41:9)
         │     at retryForSuccess (/home/avillk/repos/OpenSearch-Dashboards/test/common/services/retry/retry_for_success.ts:81:13)
         │   Error: retry.try timeout: Error: retry.try timeout: TimeoutError: Waiting for element to be located By(css selector, [data-test-subj="deleteIndexPatternButton"])
         │   Wait timed out after 10025ms
         │       at /home/avillk/repos/OpenSearch-Dashboards/node_modules/selenium-webdriver/lib/webdriver.js:842:17
         │       at process._tickCallback (internal/process/next_tick.js:68:7)
         │       at onFailure (test/common/services/retry/retry_for_success.ts:41:9)
         │       at retryForSuccess (test/common/services/retry/retry_for_success.ts:81:13)
         │       at onFailure (test/common/services/retry/retry_for_success.ts:41:9)
         │       at retryForSuccess (test/common/services/retry/retry_for_success.ts:81:13)
```

**Comment by wbeckler** [comment]
closing as redundant to other functional test issues
