### ISSUE TITLE
[Plugin functional failure] Custom doc link

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5370]
**Describe the bug**
The custom doc link test `test/plugin_functional/test_suites/doc_views_links/doc_views_links.ts` fail after this commit got merged in 2.11 branch: https://github.com/opensearch-project/OpenSearch-Dashboards/commit/3512117dcb47fe853439ab6d1791b21d0d02c9ae.

However, this commit fixed the previous problematic doc sharing functionality in the discover plugin. And the custom doc link test failed before and was modified in this PR: [https://github.com/opensearch-project/OpenSearch-Dashboards/commit/4bfc5e42308187199a752fb3985a4bda81f188bf#diff-fa7289104e843[…]e12dcb8381a6589b825](https://github.com/opensearch-project/OpenSearch-Dashboards/commit/4bfc5e42308187199a752fb3985a4bda81f188bf#diff-fa7289104e8438da83f4d53db0485a8025ffdef974040e12dcb8381a6589b825)

We should double check and confirm now after the new commit that fixes the sharing link function, if the custom doc link test is fixed without the change in the above PR.

```
1 failing
     │
     │1)    doc views links
     │       custom doc views links
     │         should render href doc view link:
     │
     │
     │       Error: expected 'http://localhost:5620/app/discover#/context/logstash-*/AU_x3_g4GFA8no6QjkYX?_g=(filters:!())&_a=(columns:!(_source),filters:!())' to sort of equal 'http://some-url/'
     │       + expected - actual
     │ 
     │       -http://localhost:5620/app/discover#/context/logstash-*/AU_x3_g4GFA8no6QjkYX?_g=(filters:!())&_a=(columns:!(_source),filters:!())
     │       +http://some-url/
     │       
     │       at Assertion.assert (packages/osd-expect/expect.js:111:11)
     │       at Assertion.eql (packages/osd-expect/expect.js:255:8)
     │       at Context.<anonymous> (test/plugin_functional/test_suites/doc_views_links/doc_views_links.ts:67:29)
     │       at runMicrotasks (<anonymous>)
     │       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     │       at Object.apply (packages/osd-test/src/functional_test_runner/lib/mocha/wrap_function.js:95:16)
```

**Comment by Willie-The-Lord** [comment]
Hi @abbyhu2000 I would like to take a look at this issue. Can you assign me? Thanks

**Comment by Willie-The-Lord** [comment]
@abbyhu2000 When setting up the functional test server, I consistently encounter an error related to incompatible snapshots. Is there something I'm overlooking?
![Screenshot 2023-10-26 at 9 26 59 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/65143821/c8f39414-fe43-465c-a617-fdfaaad2b833)

**Comment by Willie-The-Lord** [comment]
Hmm... it seems like an existing problem form `darwin-arm64`. https://github.com/opensearch-project/opensearch-build/issues/4131

**Comment by seraphjiang** [comment]
Thank you for reporting this issue. This issue has been open for a long time without recent activity, and OpenSearch Dashboards has since moved to the 3.x release line (currently 3.6, with 3.7 upcoming). The last supported 2.x release is 2.19.x.

We're closing this as part of a housekeeping effort to keep the backlog actionable. If this issue is still reproducible on a supported version (2.19.x or 3.x), please feel free to reopen this issue or file a new one with updated reproduction steps and version details.

We appreciate your contribution to OpenSearch!
