### ISSUE TITLE
[BUG][Test] App link test broke for plugin functional tests

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5385]
**Describe the bug**
There are two failed tests for app link functional tests. 

```
│2)    application links
     │       app links
     │         handles hash in urls:
     │
     │
     │       Error: expected '/app/applink_end/some-path' to sort of equal '/app/applink_end/some-path#/some/hash'
     │       + expected - actual
     │ 
     │       -/app/applink_end/some-path
     │       +/app/applink_end/some-path#/some/hash
     │       
     │       at Assertion.assert (packages/osd-expect/expect.js:111:11)
     │       at Assertion.eql (packages/osd-expect/expect.js:255:8)
     │       at Context.<anonymous> (test/plugin_functional/test_suites/application_links/redirect_app_links.ts:90:65)
     │       at processTicksAndRejections (node:internal/process/task_queues:95:5)
     │       at Object.apply (packages/osd-test/src/functional_test_runner/lib/mocha/wrap_function.js:95:16)
     │ 
     │ 
     │3)    application links
     │       app links
     │         works in a nested dom structure:
     │
     │
     │       Error: expected '/app/applink_end' to sort of equal '/app/applink_end#bang'
     │       + expected - actual
     │ 
     │       -/app/applink_end
     │       +/app/applink_end#bang
     │       
     │       at Assertion.assert (packages/osd-expect/expect.js:111:11)
     │       at Assertion.eql (packages/osd-expect/expect.js:255:8)
     │       at Context.<anonymous> (test/plugin_functional/test_suites/application_links/redirect_app_links.ts:100:65)
     │       at processTicksAndRejections (node:internal/process/task_queues:95:5)
     │       at Object.apply (packages/osd-test/src/functional_test_runner/lib/mocha/wrap_function.js:95:16)
     │ 
```

**Comment by seraphjiang** [comment]
Thank you for reporting this issue. This issue has been open for a long time without recent activity, and OpenSearch Dashboards has since moved to the 3.x release line (currently 3.6, with 3.7 upcoming). The last supported 2.x release is 2.19.x.

We're closing this as part of a housekeeping effort to keep the backlog actionable. If this issue is still reproducible on a supported version (2.19.x or 3.x), please feel free to reopen this issue or file a new one with updated reproduction steps and version details.

We appreciate your contribution to OpenSearch!
