### ISSUE TITLE
[BUG] ScopedHistory instance has fell out of scope for basePath: `/app/data-explorer`

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#5476]
**Describe the bug**

When we switch the query language in discover page, the console outputs the below error. On top of that, the action of navigating from discover page to another page will output a series of the following error as well. 

It seems like the scope history in data explorer needs to be better handled. 

```
scoped_history.ts:252 Uncaught (in promise) Error: ScopedHistory instance has fell out of navigation scope for basePath: /app/data-explorer
    at ScopedHistory.verifyActive (scoped_history.ts:252:1)
    at get location [as location] (scoped_history.ts:207:1)
    at getCurrentUrl (parse.ts:37:1)
    at getPendingUrl (osd_url_storage.ts:146:1)
    at flush (osd_url_storage.ts:135:1)
    at osd_url_storage.ts:163:1
```

**To Reproduce**
1. Go to discover page
2. Click on the toggle on query language selector on the top navigation bar. 
3. See error

**Comment by thanhinhchtom** [comment]
@joshuarrrr Can I try this one?

**Comment by abbyhu2000** [comment]
@ashwin-pc here is the screenshot recording, i started the dashboard in Incognito:

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/7e7486f2-5980-488c-9c1f-c6b4a82fe570

**Comment by lynara** [comment]
Hi,
is this related to my issue that the browser back button is not working like it did prior to 2.10 when the new discover tool got introduced?
