### ISSUE TITLE
[BUG] 2.11.0 did not start in dev mode

### ISSUE THREAD

**Issue by dbuteau** [opensearch-project/OpenSearch-Dashboards#5536]
**Describe the bug**

When launching opensearch-dashboard for first time, when launched as dev mode an internal error happen.   
I think i've followed correctly: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/DEVELOPER_GUIDE.md#getting-started-guide  

If i missed something please help me because i tried lot of things to make it work or understand what the problem is but can't found something until now  

**To Reproduce**
```console
sudo apt install nodejs npm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
npm install --global yarn
# also tried with this too (just in case)
npm i -g corepack
corepack install
#####
git clone https://github.com/opensearch-project/OpenSearch-Dashboards.git
cd OpenSearch-Dashboard
git checkout -b 2.11.0 2.11.0

export NODE_VERSION=$(cat .node-version) # 18.16.0
nvm install $NODE_VERSION
nvm use $NODE_VERSION
npm install -g uuid@latest

docker run --rm -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" --name opensearch-node opensearchproject/opensearch:2.11.0
curl -k https://admin:admin@localhost:9200/
{
  "name" : "9ed2e043be13",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "v3EYzewjT3G6xjBQjrKY4g",
  "version" : {
    "distribution" : "opensearch",
    "number" : "2.11.0",
    "build_type" : "tar",
    "build_hash" : "4dcad6dd1fd45b6bd91f041a041829c8687278fa",
    "build_date" : "2023-10-13T02:55:55.511945994Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}

cat << EOF >> config/opensearch_dashboards.yml
opensearch.hosts: ["https://localhost:9200"]
opensearch.username: "admin"
opensearch.password: "admin"
opensearch.ssl.verificationMode: none
EOF
yarn cache clean
yarn osd clean
yarn osd bootstrap
yarn start
```

It seem to start correctly:
```
yarn run v1.22.19
scripts/use_node scripts/opensearch_dashboards --dev
  log   [13:19:19.673] [info][plugins-service] Plugin "dataSourceManagement" has been disabled since the following direct or transitive dependencies are missing or disabled: [dataSource]
  log   [13:19:19.678] [info][plugins-service] Plugin "dataSource" is disabled.
  log   [13:19:19.679] [info][plugins-service] Plugin "visTypeXy" is disabled.
[agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
  log   [13:19:19.876] [info][plugins-service] Plugin initialization disabled.
  log   [13:19:19.931] [warning][savedobjects-service] Skipping Saved Object migrations on startup. Note: Individual documents will still be migrated when read or written.
np bld    log   [14:19:20.838] [info][@osd/optimizer] initialized, 48 bundles cached
np bld    log   [14:19:21.687] [info][@osd/optimizer] starting worker [1 bundle]
np bld    log   [14:19:21.694] [info][@osd/optimizer] starting worker [1 bundle]
 watching for changes  (2201 files)
  log   [13:19:22.319] [info][server] basepath proxy server running at http://localhost:5601/uan
server    log   [13:19:30.528] [info][plugins-service] Plugin "dataSourceManagement" has been disabled since the following direct or transitive dependencies are missing or disabled: [dataSource]
server    log   [13:19:30.543] [info][plugins-service] Plugin "dataSource" is disabled.
server    log   [13:19:30.544] [info][plugins-service] Plugin "visTypeXy" is disabled.
[agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
server    log   [13:19:31.056] [info][plugins-system] Setting up [38] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,apmOss,savedObjects,dashboard,visualizations,visTypeMarkdown,visTypeVega,visTypeTimeline,visTypeTable,visBuilder,visAugmenter,tileMap,regionMap,inputControlVis,visualize,management,indexPatternManagement,advancedSettings,console,dataExplorer,charts,visTypeVislib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,discover,savedObjectsManagement,bfetch]
server    log   [13:19:32.066] [info][savedobjects-service] Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations...
server    log   [13:19:32.296] [info][savedobjects-service] Starting saved objects migrations
server    log   [13:19:32.525] [info][plugins-system] Starting [38] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,apmOss,savedObjects,dashboard,visualizations,visTypeMarkdown,visTypeVega,visTypeTimeline,visTypeTable,visBuilder,visAugmenter,tileMap,regionMap,inputControlVis,visualize,management,indexPatternManagement,advancedSettings,console,dataExplorer,charts,visTypeVislib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,discover,savedObjectsManagement,bfetch]
server    log   [13:19:33.688] [info][listening] Server running at http://localhost:5603/uan
server    log   [13:19:33.898] [info][server][OpenSearchDashboards][http] http server running at http://localhost:5603/uan
np bld    log   [14:20:15.957] [success][@osd/optimizer] 2 bundles compiled successfully after 55.8 sec, watching for changes
```

but when trying to open OSD page by using the link in logs (http://localhost:5603/uan in this example)

It display an Internal Error, and this appear in log:
```console
server    log   [13:50:54.930] [error][data][opensearch] [ResponseError]: Response Error
server    log   [13:50:54.935] [error][http] ResponseError: Response Error
    at onBody (/home/.../OpenSearch-Dashboards/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)
    at IncomingMessage.onEnd (/home/.../OpenSearch-Dashboards/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)
    at IncomingMessage.emit (node:events:526:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  meta: {
    body: '',
    statusCode: 401,
    headers: {
      'x-opaque-id': 'c64ab2e1-83c5-462c-a439-f78e2954839f',
      'www-authenticate': 'Basic realm="OpenSearch Security"',
      'content-type': 'text/plain; charset=UTF-8',
      'content-length': '0'
    },
    meta: {
      context: null,
      request: [Object],
      name: 'opensearch-js',
      connection: [Object],
      attempts: 0,
      aborted: false
    }
  },
  isBoom: true,
  isServer: false,
  data: null,
  output: {
    statusCode: 401,
    payload: {
      statusCode: 401,
      error: 'Unauthorized',
      message: 'Response Error'
    },
    headers: {}
  },
  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/notAuthorized'
}
server   error  [13:50:54.899]  Error: Internal Server Error
    at HapiResponseAdapter.toInternalError (/home/.../OpenSearch-Dashboards/src/core/server/http/router/response_adapter.ts:71:19)
    at Router.handle (/home/.../OpenSearch-Dashboards/src/core/server/http/router/router.ts:304:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handler (/home/.../OpenSearch-Dashboards/src/core/server/http/router/router.ts:241:11)
    at exports.Manager.execute (/home/.../OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at Object.internals.handler (/home/.../OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at exports.execute (/home/.../OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at Request._lifecycle (/home/.../OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/request.js:371:32)
    at Request._execute (/home/.../OpenSearch-Dashboards/node_modules/@hapi/hapi/lib/request.js:281:9)
```

**Expected behavior**
No internal Error

**OpenSearch Version**
2.11.0

**Dashboards Version**
2.11.0

**Plugins**

None, minimal start

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS (WSL 2)
 - Firefox 115.5.0esr (64 bits)
 - Yarn version: 1.22.19

**Comment by dbuteau** [comment]
Ok i found the problem(i think).
TL:DR:
The following command fixed all:
```
npx browserslist@latest --update-db
```
i found it by trying the procedure with 2.9.0 and warning about this command appeared in logs, and 2.9.0 procedure worked.
So i retried with 2.11.0 executing this command before yarn osd bootstrap/yarn start, and the error had disappeared.

**Comment by abbyhu2000** [comment]
Thanks for documenting the issue and the solution. Please reopen if there are further questions.
