### ISSUE TITLE
[Test] Investigate console error in telemetry_service.test.ts

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#557]
**Describe the issue**

Currently, `telemetry_service.test.ts` prints out console errors when run the unit test. To make a clean unit test, we want to explore the reasons for these errors/warnings and decide whether we could fix or remove them. 

```
console.error
    Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchError (/home/anan/work/OpenSearch-Dashboards/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
        at Request.client.on.err (/home/anan/work/OpenSearch-Dashboards/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:674:20)
        at Request.emit (events.js:203:15)
        at Request.onRequestError (/home/anan/work/OpenSearch-Dashboards/node_modules/request/request.js:877:8)
        at ClientRequest.emit (events.js:198:13)
        at Socket.socketErrorListener (_http_client.js:401:9)
        at Socket.emit (events.js:198:13)
        at emitErrorNT (internal/streams/destroy.js:91:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
        at process._tickCallback (internal/process/next_tick.js:63:19) undefined

      at VirtualConsole.on.e (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr-utils.js:63:53)
      at Request.client.on.err (node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:674:20)
      at Request.onRequestError (node_modules/request/request.js:877:8)

```

**To Reproduce**
Run:`yarn test:jest {path to telemetry_service.test.ts}`

**Expected behavior**
    
explore each problem unit test cases and investigate each question:
   
- what causes the console error or issues?

- should this unit test log this error or warning message?

- if answer to the above question is no, then can we fix it?

The final output is expected to be a cleaned unit test with un-necessary error/warnings been removed. 

**OpenSearch Version**
OpenSearch 1.0.0

**Dashboards Version**
Dashboards 1.0.0

**Comment by ananzh** [comment]
I don't see this issue any more. Close it.
