### ISSUE TITLE
[BUG] Can't enable proxy and basic auth at the same time

### ISSUE THREAD

**Issue by samk-acw** [opensearch-project/OpenSearch-Dashboards#5655]
**description**

I've setup proxy authentication and it works fine, however I want to also allow basicauth as well to allow non-SSO users, but it doesn't seem to be supported. 
Multiple auth types is possible according to https://opensearch.org/docs/latest/security/configuration/multi-auth/ but this doesn't mention proxy auth.
Attempting to configure both proxy and basicauth results in opensearch-dashboards not being able to start, showing "Error: Unsupported authentication type: proxy"

**To Reproduce**
1. set proxy and basicauth types and multiple_auth_enabled in opensearch-dashboards.yml:
```
opensearch_security.auth.type: ["proxy","basicauth"]
opensearch_security.auth.multiple_auth_enabled: true
```
2. start opensearch-dashboards
3. startup fails and logs the following:

> Error: Unsupported authentication type: proxy
    at MultipleAuthentication.init (/usr/share/opensearch-dashboards/plugins/securityDashboards/server/auth/types/multiple/multi_auth.ts:97:17)
    at createAuthentication (/usr/share/opensearch-dashboards/plugins/securityDashboards/server/auth/auth_handler_factory.ts:46:3)
    at getAuthenticationHandler (/usr/share/opensearch-dashboards/plugins/securityDashboards/server/auth/auth_handler_factory.ts:91:37)
    at SecurityPlugin.setup (/usr/share/opensearch-dashboards/plugins/securityDashboards/server/plugin.ts:119:39)
    at PluginsSystem.setupPlugins (/usr/share/opensearch-dashboards/src/core/server/plugins/plugins_system.js:101:24)
    at PluginsService.setup (/usr/share/opensearch-dashboards/src/core/server/plugins/plugins_service.js:117:19)
    at Server.setup (/usr/share/opensearch-dashboards/src/core/server/server.js:275:26)
    at Root.setup (/usr/share/opensearch-dashboards/src/core/server/root/index.js:70:14)
    at bootstrap (/usr/share/opensearch-dashboards/src/core/server/bootstrap.js:133:5)
    at Command.<anonymous> (/usr/share/opensearch-dashboards/src/cli/serve/serve.js:193:5)

**Expected behavior**
dashboards should allow proxy auth in combination with other auth types - eg use proxy auth if the relevant headers are present and request is coming from an allowed proxy, otherwise go to the regular login page.

**OpenSearch Version**
2.11.1

**Dashboards Version**
2.11.1

**Plugins**

defaults

**Host/Environment (please complete the following information):**
Debian 12

**Comment by kavilla** [comment]
Hello @samk-acw, thank you for opening.

@opensearch-project/admin, can you please move this to https://github.com/opensearch-project/security-dashboards-plugin
