### ISSUE TITLE
Support for TLS certificates withRSA public key size of 3096 and  ECDSA signing algorithm.

### ISSUE THREAD

**Issue by jpelletier412** [opensearch-project/OpenSearch-Dashboards#5721]
**Is your feature request related to a problem? Please describe.**

We are attempting to use TLS certificates with RSA public key size of 3096 and ECDSA signing algorithm and get an error when Opensearch Dashboards initializes:
`/usr/share/opensearch-dashboards/src/core/server/http/ssl_config.js:124
        throw new Error(`Did not find certificate in keystore at [keystore.path].`);
              ^
Error: Did not find certificate in keystore at [keystore.path].
    at new SslConfig (/usr/share/opensearch-dashboards/src/core/server/http/ssl_config.js:124:15)
    at new HttpConfig (/usr/share/opensearch-dashboards/src/core/server/http/http_config.js:175:16)
    at MapSubscriber.project (/usr/share/opensearch-dashboards/src/core/server/http/http_service.js:61:177)
    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)
    at CombineLatestSubscriber.notifyNext (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/observable/combineLatest.js:97:34)
    at InnerSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)
    at DistinctUntilChangedSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)
    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject._subscribe (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/ReplaySubject.js:80:28)
    at ReplaySubject.Observable._trySubscribe (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Observable.js:44:25)`

We tried in the latest 2.11.1 version and the error is still present so it does not look like Dashboards supports this type of certificate. 
Here is example of certificate info we would like to use:
![certificate](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/143456153/ed26156b-2e01-47c9-9512-e5d29475d6fb)

**Describe the solution you'd like**

For Opensearch Dashboards to support TLS certificates with RSA key size of 3096 and ECDSA signing algorithm.

**Describe alternatives you've considered**

For now we are using standard RSA key size of 2048 and SHA-256 signing algorithm.

**Comment by merlinz01** [comment]
Just an observation: 3096 is not a standard key size; 4096 would be more common.
