### ISSUE TITLE
Unknown Sass implementation "sass-embedded"

### ISSUE THREAD

**Issue by Doberick** [opensearch-project/OpenSearch-Dashboards#5994]
**Describe the bug**

When I use the following command:

`yarn build`

Inside a plugin folder, I get the following error:

         │          ERROR in ./public/index.scss?v7dark (/Users/myuser/Projects/OpenSearch-Dashboards/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-0-1!/Users/myuser/Projects/OpenSearch-Dashboards/node_modules/postcss-loader/dist/cjs.js??ref--6-oneOf-0-2!/Users/myuser/Projects/OpenSearch-Dashboards/node_modules/comment-stripper??ref--6-oneOf-0-3!/Users/myuser/Projects/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-0-4!./public/index.scss?v7dark)
         │          Module Error (from /Users/myuser/Projects/OpenSearch-Dashboards/node_modules/sass-loader/dist/cjs.js):
         │          Unknown Sass implementation "sass-embedded".
         │          Error: Unknown Sass implementation "sass-embedded".
         │              at getSassImplementation (/Users/myuser/Projects/OpenSearch-Dashboards/node_modules/sass-loader/dist/utils.js:80:27)
         │              at Object.loader (/Users/myuser/Projects/OpenSearch-Dashboards/node_modules/sass-loader/dist/index.js:27:59)
         │           @ ./public/index.scss?v7dark 2:26-318
         │           @ ./public/index.scss
         │           @ ./public/index.ts
         │           @ /Users/myuser/Projects/OpenSearch-Dashboards/packages/osd-optimizer/target/worker/entry_point_creator.js

**To Reproduce**
1. Clone the repository.
2. Switch to branch 2.11
3. run`nvm use 18.12.0` and  `yarn install`
4. run  `node scripts/generate_plugin.js myPlugin`
5. run `cd plugins/myPlugin` and `yarn build` 

**Expected behavior**
The command should run without errors

**Comment by ananzh** [comment]
Could you just bootstrap and see if the problem is resolved?
