### ISSUE TITLE
BUG] Internal Server Error HapiResponseAdapter.toInternalError

### ISSUE THREAD

**Issue by StefanSa** [opensearch-project/OpenSearch-Dashboards#6121]
**Describe the bug**
Hi there
We need your help as we are currently unable to find a solution to the problem.
We have installed wazuh-dashboard v4.7.2 (os 2.8).
Worked without problem until we installed opensearch-dashboards v2.12 on the same server.
Since then wazuh-dashboard crashes with these errors.
```
2024-03-12T16:22:17.408942+01:00 MOS-IT-pWAZUH-01 opensearch-dashboards[1217]: {"type":"error","@timestamp":"2024-03-12T15:22:17Z","tags":[],"pid":1217,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toInternalError (/usr/share/wazuh-dashboard/src/core/server/http/router/response_adapter.js:80:19)\n    at Object.interceptAuth [as authenticate] (/usr/share/wazuh-dashboard/src/core/server/http/lifecycle/auth.js:151:34)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at exports.Manager.execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n at module.exports.internals.Auth._authenticate (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/auth.js:273:30)\n at
Request._lifecycle (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:371:32)\n    at Request._execute (/usr/share/wazuh-dashboard/node_modules/@hapi/hapi/lib/request.js:281:9)"},"url":"https://wazuh.xxxlocal/","message":"Internal Server Error"}
```
```
2024-03-12T16:22:17.410108+01:00 MOS-IT-pWAZUH-01 opensearch-dashboards[1217]: {"type":"response","@timestamp":"2024-03-12T15:22:17Z","tags":[],"pid":1217,"method":"get","statusCode":500,"req":{"url":"/","method":"get","headers":{"host":"wazuh.xxxx.local","connection":"keep-alive","cache-control":"max-age=0","sec-ch-ua":"\"Chromium\";v=\"122\", \"Not(A:Brand\";v=\"24\", \"Microsoft Edge\";v=\"122\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br","accept-language":"de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"}
,"remoteAddress":"172.16.33.110","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"},"res":{"statusCode":500,"responseTime":369,"contentLength":9},"message":"GET / 500 369ms - 9.0B"}
```
opensearch-dashboards v2.12 itself has no problems.
The wazuh-dashboard is installed in different paths, which is whyi i don't understand why such problems occur.
A new installation does not help either.
i would be pleased if someone had an idea how to solve this problem.

**Comment by AMoo-Miki** [comment]
@StefanSa, the only way I can think of the two interfering with each other is if they were configured to use the same ip:port and as such, one wasn't actually running. Since the error is showing up in Wazuh, you would be better helped if you ask for their inputs.

**Comment by AMoo-Miki** [comment]
I am glad you found the problem and thanks for letting us know.
