### ISSUE TITLE
[BUG] - Controls Visualization throws Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by nastri83** [opensearch-project/OpenSearch-Dashboards#6676]
**Describe the bug**

This just recently started happening when trying to create or edit a Controls visualization. I'm unable to edit any of my existing controls visualizations or create a new one because a Cannot read properties of undefined (reading 'toLowerCase') error message displays.

It was happening in 2.11, so I deleted the containers and redeployed using docker compose. I'm now up to 2.13 and it's still happening.

**To Reproduce**
1. Go to Visualize
2. Click on Create Visualization
3. Select Controls
4. Choose Options List or Range Slider
5. Click Add
6. See error: 
Error: Cannot read properties of undefined (reading 'toLowerCase')
    at fF (http://10.246.151.248:5601/7550/bundles/osd-ui-shared-deps/osd-ui-shared-deps.@elastic.js:609:2446228)
    at pF (http://10.246.151.248:5601/7550/bundles/osd-ui-shared-deps/osd-ui-shared-deps.@elastic.js:609:2446351)
    at http://10.246.151.248:5601/7550/bundles/osd-ui-shared-deps/osd-ui-shared-deps.@elastic.js:609:2446712
    at Array.forEach (<anonymous>)
    at dF (http://10.246.151.248:5601/7550/bundles/osd-ui-shared-deps/osd-ui-shared-deps.@elastic.js:609:2446525)
    at value (http://10.246.151.248:5601/7550/bundles/osd-ui-shared-deps/osd-ui-shared-deps.@elastic.js:609:2467189)
    at bi (http://10.246.151.248:5601/7550/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:435:48655)
    at Da (http://10.246.151.248:5601/7550/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:435:68735)
    at gs (http://10.246.151.248:5601/7550/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:435:105471)
    at uc (http://10.246.151.248:5601/7550/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:435:96718)

**Expected behavior**
The dropdown menu creation UI will show.

**OpenSearch Version**
2.13.0

**Dashboards Version**
2.13.0

**Plugins**
Logstash

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: SLES 15 SP4
 - Browser and version [e.g. 22]: Edge 124.0.2478.51

**Additional context**

**Comment by kavilla** [comment]
Hey @nastri83 do you mind sharing your aggregation config which should be in your URL (removing all the sensitive information) or from within the saved objects inspect view.

**Comment by nastri83** [comment]
Sure. This is the url that is displayed when I hit the error.

http://<server IP>:5601/app/visualize#/create?type=input_control_vis&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(filters:!(),linked:!f,query:(language:kuery,query:''),uiState:(),vis:(aggs:!(),params:(controls:!(),pinFilters:!f,updateFiltersOnChange:!f,useTimeFilter:!f),title:'',type:input_control_vis))

**Comment by ashwin-pc** [comment]
@nastri83 I'm unable to reproduce your issue based on the reproduction steps provided. Here is a link to the playground where i followed the steps you mentioned without any issues: 

https://playground.opensearch.org/app/visualize#/create?type=input_control_vis&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(filters:!(),linked:!f,query:(language:kuery,query:''),uiState:(),vis:(aggs:!(),params:(controls:!(),pinFilters:!f,updateFiltersOnChange:!f,useTimeFilter:!f),title:'',type:input_control_vis))

If you could attach a video of the issue with the console window open it would help reproducing the error on our end. See a screenshot below of how you can do this.
![Screenshot 2024-05-06 at 8 53 52 PM](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/20453492/300c717a-4ae6-4a32-81bc-58ea546f5040)

**Comment by nastri83** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/assets/9575538/769e901e-10b5-438a-ba09-093a3c8ed313

Attaching video of bug
