### ISSUE TITLE
[BUG] Failed to fetch error on Discover page

### ISSUE THREAD

**Issue by saketmht** [opensearch-project/OpenSearch-Dashboards#6802]
**Describe the bug**

We have OS and OSD setup on k8s with Keycloak. The OSD Discover page seems to work fine for around 30 mins before it starts giving `failed to fetch` error when using the search. We have to refresh the page everytime to get it back to normal and after a while again the same issue happens.

```
TypeError: Failed to fetch
    at Fetch._callee3$ (https://osd.vmi.system.shoe.v8o.com/34/bundles/core/core.entry.js:15:583674)
    at tryCatch (https://osd.vmi.system.shoe.v8o.com/34/bundles/plugin/indexManagementDashboards/indexManagementDashboards.plugin.js:1:138399)
    at Generator.invoke [as _invoke] (https://osd.vmi.system.shoe.v8o.com/34/bundles/plugin/indexManagementDashboards/indexManagementDashboards.plugin.js:1:142350)
    at Generator.throw (https://osd.vmi.system.shoe.v8o.com/34/bundles/plugin/indexManagementDashboards/indexManagementDashboards.plugin.js:1:139538)
    at fetch_asyncGeneratorStep (https://osd.vmi.system.shoe.v8o.com/34/bundles/core/core.entry.js:15:577704)
    at _throw (https://osd.vmi.system.shoe.v8o.com/34/bundles/core/core.entry.js:15:578112)
```

This issue is mostly seen with larger indices.

**To Reproduce**
1. Go to Discover page
2. Perform some searches
3. After 30-60mins

**Expected behavior**

**OpenSearch Version**
2.3.0

**Dashboards Version**
2.3.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

![image (4)](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/54639179/1c0ff627-b9e1-4fd0-b17e-e14d5307cf14)

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by huyaboo** [comment]
So after the 30 minutes, if you refreshed the page, are you forced to reauthenticate? If yes, its likely that your session has timed out.
