### ISSUE TITLE
[BUG] data_source.enabled: false causes getDataSourceMenu to fail

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#7154]
**Describe the bug**

Some recent commit in OSD started throwing the following error: 

```
create_getter_setter.ts:34 Uncaught Error: UiSettings was not set.
    at get (create_getter_setter.ts:34:1)
    at createDataSourceMenu (create_data_source_menu.tsx:14:1)
    at Object.getDataSourceMenu (plugin.ts:79:1)
    at top-nav-menu.tsx:32:1
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
```

when data_source.enabled is set to false or not set (false default).
**To Reproduce**
Go to some usage of DataSourceMenu and set data_source.enabled as false or not set. 

**Expected behavior**
Page doesn't crash
**OpenSearch Version**
main
**Dashboards Version**
main
**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by kavilla** [comment]
@BionIT would you be able to take a look at this?

**Comment by BionIT** [comment]
> @BionIT would you be able to take a look at this?

Yes, just took a look, will sync with @RyanL1997 for fix
