### ISSUE TITLE
[BUG][opensearch-dashboards] opensearch_security.cookie.secure is not a valid configuration option

### ISSUE THREAD

**Issue by jpanynines** [opensearch-project/OpenSearch-Dashboards#8810]
**Describe the bug**
When using the security plugin, the following error is shown in the logs:
```
{"type":"log","@timestamp":"2024-10-22T02:10:49Z","tags":["fatal","root"],"pid":8,"message":"InvalidConfigurationError: Unknown configuration key(s): \"opensearch_security.cookie.secure\". Check for spelling errors and ensure that expected plugins are installed.\n    at ensureValidConfiguration (/var/vcap/data/packages/opensearch-dashboards/caa6e98035eac8fd70825811ba3a41f635aec962/src/core/server/legacy/config/ensure_valid_configuration.js:50:11)\n    at Server.setup (/var/vcap/data/packages/opensearch-dashboards/caa6e98035eac8fd70825811ba3a41f635aec962/src/core/server/server.js:156:5)\n    at Root.setup (/var/vcap/data/packages/opensearch-dashboards/caa6e98035eac8fd70825811ba3a41f635aec962/src/core/server/root/index.js:60:14)\n    at bootstrap (/var/vcap/data/packages/opensearch-dashboards/caa6e98035eac8fd70825811ba3a41f635aec962/src/core/server/bootstrap.js:113:5)\n    at Command.<anonymous> (/var/vcap/data/packages/opensearch-dashboards/caa6e98035eac8fd70825811ba3a41f635aec962/src/cli/serve/serve.js:192:5) {\n  code: 'InvalidConfig',\n  processExitCode: 64,\n  cause: undefined\n}"}
```
**To Reproduce**
1. Set the configuration on opensearch_dashboards.yml (here is a snippet of the config file for context):
```
# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the OpenSearch Dashboards server to the browser.
server.ssl.enabled: true
server.ssl.certificate: /var/vcap/jobs/opensearch-dashboards/certificates/opensearch-dashboard/cert.pem
server.ssl.key: /var/vcap/jobs/opensearch-dashboards/certificates/opensearch-dashboard/key.pem


# Optional settings that provide the paths to the PEM-format SSL certificate and key files.
# These files are used to verify the identity of OpenSearch Dashboards to OpenSearch
opensearch.ssl.certificate: /var/vcap/jobs/opensearch-dashboards/certificates/opensearch/server.pem
opensearch.ssl.key: /var/vcap/jobs/opensearch-dashboards/certificates/opensearch/server-key.pem

# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your OpenSearch instance.
opensearch.ssl.certificateAuthorities: ["/var/vcap/jobs/opensearch-dashboards/certificates/opensearch/ca.pem"]

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
opensearch.ssl.verificationMode: full

opensearch_security.cookie.secure: true
```
2. Start opensearch-dashboards
3. Check logs for the error

**Expected behavior**
This configuration option should be valid, as stated in the documentation: https://opensearch.org/docs/latest/install-and-configure/install-dashboards/tls/

**OpenSearch Version**
2.16

**Dashboards Version**
2.16

**Plugins**
```
os/6dc97238-a182-4cad-b02a-fcd6b59d1357:/var/vcap/packages/opensearch/bin# ./opensearch-plugin list
opensearch-alerting
opensearch-index-management
opensearch-job-scheduler
opensearch-notifications
opensearch-notifications-core
opensearch-security
repository-azure
repository-s3
```
**Host/Environment (please complete the following information):**
 - OS: Ubuntu Jammy

**Comment by dblock** [comment]
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/andrross/), [4](https://github.com/krisfreedain), [5](https://github.com/andy-k-improving)]
