### ISSUE TITLE
[BUG] DQL-searching using wildcards for field names and values fail 

### ISSUE THREAD

**Issue by hbrodin** [opensearch-project/OpenSearch-Dashboards#9094]
**Describe the bug**
When filtering the results for a specific manufacturer in either PPL or SQL-mode it seems like results not having that manufacturer is returned

**To Reproduce**

1. Login anonymous in the future playground.
2. Select the **OTEL demo environment**.
3. Select **Discover** from the menu on the left hand side
4. In the data source selection dropdown, select `opensearch_dashboards_sample_data_logs`
5. In DQL-mode, search for `machine*: *7*`
6. Notice how no results are produce and the Search Error `Error
    at fetch_Fetch.fetchResponse (https://future.playground.opensearch.org/11925136331/bundles/core/core.entry.js:15:413871)
    at async interceptResponse (https://future.playground.opensearch.org/11925136331/bundles/core/core.entry.js:15:408634)
    at async https://future.playground.opensearch.org/11925136331/bundles/core/core.entry.js:15:411601` is presented.

**Expected behavior**
Any fields matching `machine*`, such as `machine.os` and `machine.ram` and having a 7 in any of those fields be presented in the results view.
 
**OpenSearch Version**

2.18

**Dashboards Version**

2.18

**Plugins**

Alerting, anomaly-detection, asynchronous-search, cross-cluster-replication, custom-codecs, flow-framework, geospatial, index-management, job-scheduler, knn, ml, neural-search, notifications, notifications-core, observability, performance-analyzer, reports-scheduler, security, security-analytics, skills, sql, system-templates, query-insights

**Screenshots**

N/A

**Host/Environment:**

 - OS: macOS
 - Browser and version Google Chrome, version 131.0.6778.205

**Additional context**
N/A

**Comment by krisfreedain** [comment]
[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/krisfreedain), [2](https://github.com/andrross/), [3](https://github.com/reta)

**Comment by ashwin-pc** [comment]
This is because machine.os and machine.ram are both nested fields of the machine field.
